Repository TeamNewPipe/NewPipe, pull requests merged in 2019-12, with the labels that each got.

#2679 more dl features
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
  app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java
  app/src/main/java/org/schabi/newpipe/streams/WebMReader.java
  app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
  app/src/main/java/org/schabi/newpipe/util/SecondaryStreamHelper.java
  app/src/main/java/us/shandian/giga/get/DownloadInitializer.java
  app/src/main/java/us/shandian/giga/get/DownloadMission.java
  app/src/main/java/us/shandian/giga/get/DownloadMissionRecover.java
  app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
  app/src/main/java/us/shandian/giga/get/DownloadRunnableFallback.java
  app/src/main/java/us/shandian/giga/get/FinishedMission.java
  app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.java
  app/src/main/java/us/shandian/giga/io/ChunkFileInputStream.java
  app/src/main/java/us/shandian/giga/io/CircularFileWriter.java
  app/src/main/java/us/shandian/giga/io/ProgressReport.java
  app/src/main/java/us/shandian/giga/postprocessing/OggFromWebmDemuxer.java
  app/src/main/java/us/shandian/giga/postprocessing/Postprocessing.java
  app/src/main/java/us/shandian/giga/service/DownloadManager.java
  app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/java/us/shandian/giga/ui/common/Deleter.java
  app/src/main/java/us/shandian/giga/ui/common/ProgressDrawable.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
  app/src/main/java/us/shandian/giga/util/Utility.java
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-be/strings.xml
  app/src/main/res/values-cmn/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl-rBE/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: downloader

#2820 Remember caption option in player, closes #2811
  app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
  app/src/main/res/values/settings_keys.xml
Labels: enhancement, player

#2201 PeerTube support
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
  app/src/main/java/org/schabi/newpipe/util/PeertubeHelper.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/res/drawable-hdpi/ic_kiosk_local_black_24dp.png
  app/src/main/res/drawable-hdpi/ic_kiosk_local_white_24dp.png
  app/src/main/res/drawable-hdpi/ic_kiosk_recent_black_24dp.png
  app/src/main/res/drawable-hdpi/ic_kiosk_recent_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_kiosk_local_black_24dp.png
  app/src/main/res/drawable-mdpi/ic_kiosk_local_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_kiosk_recent_black_24dp.png
  app/src/main/res/drawable-mdpi/ic_kiosk_recent_white_24dp.png
  app/src/main/res/drawable-nodpi/place_holder_peertube.png
  app/src/main/res/drawable-xhdpi/ic_kiosk_local_black_24dp.png
  app/src/main/res/drawable-xhdpi/ic_kiosk_local_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_kiosk_recent_black_24dp.png
  app/src/main/res/drawable-xhdpi/ic_kiosk_recent_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_kiosk_local_black_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_kiosk_local_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_kiosk_recent_black_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_kiosk_recent_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_kiosk_local_black_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_kiosk_local_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_kiosk_recent_black_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_kiosk_recent_white_24dp.png
  app/src/main/res/layout-v21/drawer_header.xml
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/layout/drawer_layout.xml
  app/src/main/res/layout/fragment_instance_list.xml
  app/src/main/res/layout/instance_spinner_item.xml
  app/src/main/res/layout/instance_spinner_layout.xml
  app/src/main/res/layout/item_instance.xml
  app/src/main/res/values-v21/styles_services.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors_services.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/styles_services.xml
  app/src/main/res/xml/content_settings.xml
Labels: deep review required, enhancement, peertube

#2724 [Bug Fixed] Playlists With No Uploader No Longer Crash The App When Added To Users Library
  app/src/main/java/org/schabi/newpipe/database/playlist/model/PlaylistRemoteEntity.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java
  app/src/main/res/values/strings.xml
Labels: bug

#2569 Black navigation bar for black theme
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#2744 Adjustable seek duration
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/video_audio_settings.xml
Labels: player

#2792 Enabling TLS1.1/1.2 on Android 4.4 devices (API 19/KitKat)
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/util/TLSSocketFactoryCompat.java
Labels: bug, device/software specific, peertube, soundcloud

#2875 Fixed issues #2838 #2797 #2773
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Labels: bug, downloader

#2636 Add local playlist to queue when long clicking on 'Background/Popup'
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Labels: enhancement

#2912 Fix for player access out of its creation thread
  app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
Labels: bug, player

#2879 Add support for Occitan language
  app/src/main/res/values-oc/strings.xml
Labels: localisation / translation
