Repository TeamNewPipe/NewPipe, pull requests merged in 2019-10, with the labels that each got.

#2646 check if last byte in the block is downloaded
  app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
Labels: bug

#2655 Improve Accessebility for blind people
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/res/layout-v21/drawer_header.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#2535 Add missing dependencies inherited from NewPipeExtractor into NewPipe
  app/build.gradle
Labels: bug

#2672 fix scrolling in video detail fragment. fixes #2627
  app/build.gradle
  app/src/main/java/android/support/design/widget/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: GUI

#2695 Clear search box has now only one animation - issue #2644 solved
  app/src/main/res/layout/toolbar_search_layout.xml
Labels: GUI
