Repository TeamNewPipe/NewPipe, pull requests merged in 2020-07, with the labels that each got.

#3837 Fix audio/video desync caused by floating point cumulative errors
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
Labels: ASAP, bug, player

#3845 add privacytools.io peertube instance to manifest
  app/src/main/AndroidManifest.xml
Labels: enhancement, peertube

#3843 Drop writting application metadata in muxed files
  app/src/main/java/org/schabi/newpipe/streams/DataReader.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
  app/src/main/java/org/schabi/newpipe/streams/OggFromWebMWriter.java
  app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
  checkstyle-suppressions.xml
Labels: downloader

#3579 Add Markdown export of crash logs
  app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
  app/src/main/res/layout/activity_error.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#3471 Display search suggestion: did you mean & showing result for
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#3441 Next page stuff
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/DefaultKioskFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/ChannelPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlaylistPlayQueue.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
Labels: enhancement

#3920 Fix lingering focus highlight overlay
  app/src/main/java/org/schabi/newpipe/views/FocusOverlayView.java
Labels: Android TV

#3984 Fix color of correct / suggested search term
  app/src/main/res/layout/fragment_search.xml
Labels: bug

#3982 Fix ACRA bug reports not containing stack trace
  app/build.gradle
  app/src/debug/java/org/schabi/newpipe/DebugApp.kt
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/report/AcraReportSenderFactory.java
Labels: ASAP, bug
