Repository TeamNewPipe/NewPipe, pull requests merged in 2020-06, with the labels that each got.

#3698 avoid duplicate: use openUrlInBrowser instead of openWebsite
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
Labels: enhancement

#3759 Fix search crash: adapter array index out of bounds
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
Labels: Android TV

#3437 Fast rewind forward in background activity
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/res/layout-land/activity_player_queue_control.xml
  app/src/main/res/layout/activity_player_queue_control.xml
  app/src/main/res/menu/menu_play_queue.xml
Labels: enhancement

#3752 Update to ExoPlayer 2.11.6
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
Labels: player

#3406 Add possibility to open PeerTube links in NP for some instances (without needing to share to NP)
  app/src/main/AndroidManifest.xml
Labels: peertube

#3787 Fixes enqueue resuming paused videos
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
Labels: bug, player

#3822 Fix queue channel name color for some devices
  app/src/main/res/layout/activity_player_queue_control.xml
Labels: GUI, bug

#3373 Add search for subscription picker in the feed group dialog
  app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
  app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionEntity.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/EmptyPlaceholderItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
  app/src/main/res/layout/dialog_feed_group_create.xml
  app/src/main/res/layout/toolbar_search_layout.xml
  app/src/main/res/menu/menu_feed_group_dialog.xml
Labels: GUI, enhancement, feed
