Repository TeamNewPipe/NewPipe, pull requests merged in 2020-10, with the labels that each got.

#4347 Player rebind
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: player

#4350 Disabled commenter image view on LoadThumbnail set to false
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/res/layout/list_comments_item.xml
  app/src/main/res/values/dimens.xml
Labels: GUI, enhancement

#4360 Player overlays now centered
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/play_queue_item.xml
  app/src/main/res/layout/player.xml
Labels: bug, player

#4362 Random fixes and improvements
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/player.xml
Labels: GUI, player

#4365 Update to PrettyTime 4.0.6
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: localisation / translation

#4374 Norwegian Bokmål fastlane support
  fastlane/metadata/android/nb-rNO/changelogs/954.txt
  fastlane/metadata/android/nb-rNO/full_description.txt
  fastlane/metadata/android/nb-rNO/short_description.txt
Labels: localisation / translation

#4378 Replace long comments with check boxes in the Bug Report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: meta

#4379 Add check boxes to Feature Request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: meta

#4338 Use DisplayCutoutCompat in VideoPlayerImpl.
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
Labels: player

#4410 Notification fixes
  app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
Labels: bug

#4354 Improve age restriction and yt restricted content strings
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: localisation / translation

#4476 Two finger to close player gesture
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
Labels: enhancement, player

#4317 Pull request template reworked
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#4453 Add button in settings to clear reCAPTCHA cookies
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: enhancement, privacy & data protection

#4550 Don't rearrange lists by dragging the thumbnails
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItemBuilder.java
Labels: GUI, bug, player

#4554 Translates shortened notation of numbers
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: localisation / translation

#4345 Fix PlaylistAppendDialog showing when no local playlists exist
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistDAO.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Labels: GUI, bug

#4549 Fix IllegalStateException after onSaveInstanceState
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: bug
