Repository TeamNewPipe/NewPipe, pull requests merged in 2020-01, with the labels that each got.

#2771 Limit amount of notification thumbnail updates in background player
  app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
Labels: bug, player

#2871 make main page tabs scrollable and hide when there is only a single tab
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/views/ScrollableTabLayout.java
  app/src/main/res/layout/fragment_main.xml
Labels: GUI, bug

#2906 add opus file extension
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
Labels: downloader

#2935 Spelling: Could not, PeerTube, HTTPS, URL
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#2717 Add option to delete files when clearing finished downloads
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
  app/src/main/res/menu/download_menu.xml
  app/src/main/res/values/strings.xml
Labels: downloader, enhancement

#2966 /c/ channel links support & update extractor version
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: youtube

#2960 Issue #2254
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/java/org/schabi/newpipe/util/Constants.java
  app/src/main/res/menu/download_menu.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/menu/menu_about.xml
  app/src/main/res/menu/menu_play_queue.xml
Labels: GUI, enhancement

#2957 Rewrite ttml conversion
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/streams/SrtFromTtmlWriter.java
  app/src/main/java/org/schabi/newpipe/streams/SubtitleConverter.java
  app/src/main/java/us/shandian/giga/postprocessing/TtmlConverter.java
Labels: bug, downloader

#2958 fix #2889
  app/src/main/java/us/shandian/giga/postprocessing/Postprocessing.java
  app/src/main/java/us/shandian/giga/service/DownloadManager.java
Labels: bug, downloader

#2917 Allow a BasePlayer to start paused
  app/src/main/java/org/schabi/newpipe/player/BackgroundPlayerActivity.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayerActivity.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: player

#2310 Add send to Kodi button to player next to share button
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/util/KoreUtil.java
  app/src/main/res/layout-large-land/activity_main_player.xml
  app/src/main/res/layout/activity_main_player.xml
Labels: enhancement

#3032 Fixes #3021
  app/src/main/java/us/shandian/giga/get/DownloadMission.java
Labels: bug, downloader
