Repository TeamNewPipe/NewPipe, pull requests merged in 2020-05, with the labels that each got.

#3502 Allow time ago debug setting translation
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#2727 Restricted mode setting for youtube
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
  app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/CookieUtils.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: enhancement, youtube

#3511 Ktlint
  app/build.gradle
  app/src/androidTest/java/org/schabi/newpipe/database/AppDatabaseTest.kt
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
  app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedGroupDAO.kt
  app/src/main/java/org/schabi/newpipe/database/feed/model/FeedEntity.kt
  app/src/main/java/org/schabi/newpipe/database/feed/model/FeedGroupEntity.kt
  app/src/main/java/org/schabi/newpipe/database/feed/model/FeedGroupSubscriptionEntity.kt
  app/src/main/java/org/schabi/newpipe/database/feed/model/FeedLastUpdatedEntity.kt
  app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntry.kt
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt
  app/src/main/java/org/schabi/newpipe/database/stream/StreamStatisticsEntry.kt
  app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamDAO.kt
  app/src/main/java/org/schabi/newpipe/database/stream/model/StreamEntity.kt
  app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedState.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedEventManager.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/FeedGroupIcon.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/decoration/FeedGroupCarouselDecoration.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialog.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialogViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/EmptyPlaceholderItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupAddItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupCardItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupCarouselItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupReorderItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedImportExportItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderWithMenuItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerIconItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/settings/custom/DurationListPreference.kt
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
  app/src/main/java/org/schabi/newpipe/util/ExceptionUtils.kt
  app/src/main/java/org/schabi/newpipe/util/urlfinder/UrlFinder.kt
  app/src/main/java/org/schabi/newpipe/views/FocusAwareSeekBar.java
  app/src/main/java/us/shandian/giga/get/DownloadMission.java
  app/src/main/java/us/shandian/giga/get/sqlite/FinishedMissionStore.java
  app/src/main/java/us/shandian/giga/io/FileStreamSAF.java
  app/src/main/java/us/shandian/giga/io/StoredDirectoryHelper.java
  app/src/main/java/us/shandian/giga/io/StoredFileHelper.java
  app/src/main/java/us/shandian/giga/ui/common/ToolbarActivity.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
  app/src/main/res/menu/menu_local_playlist.xml
  app/src/test/java/org/schabi/newpipe/local/subscription/FeedGroupIconTest.kt
  app/src/test/java/org/schabi/newpipe/util/ExceptionUtilsTest.kt
  app/src/test/java/org/schabi/newpipe/util/urlfinder/UrlFinderTest.kt
Labels: meta

#3545 Fix Kodi button showing up with unsupported services
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/util/KoreUtil.java
  app/src/main/res/layout-large-land/activity_main_player.xml
  app/src/main/res/layout/activity_main_player.xml
Labels: bug, multiservice

#3337 Block the gesture when touch it from NavigationBar or StatusBar.
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
Labels: player

#3565 Change retry & subscribe buttons background color based on service color
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/channel_header.xml
  app/src/main/res/layout/error_retry.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles_misc.xml
Labels: GUI, enhancement

#3513 Update to ExoPlayer 2.11.4
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSourcePlaylist.java
  app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
Labels: player

#3613 Fix download dialog freeze
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  checkstyle-suppressions.xml
Labels: bug

#3618 Improve long-press menu strings
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#3501 Open in browser button now really opens in browser
  app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
Labels: bug

#3680 Open the correct kiosk
  app/src/main/java/org/schabi/newpipe/MainActivity.java
Labels: ASAP, GUI, bug

#3679 Enable requestLegacyExternalStorage
  app/src/main/AndroidManifest.xml
Labels: ASAP, bug
