Repository TeamNewPipe/NewPipe, pull requests merged in 2020-02, with the labels that each got.

#3004 ask for display over other apps permission in settings
  app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
  app/src/main/res/values/strings.xml
Labels: bug

#2921 Add language selector to change the app language
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
  app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.java
  app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
  app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: enhancement, localisation / translation

#2954 Rename local playlist by long-clicking in BookmarkFragment.
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/res/layout/dialog_bookmark.xml
Labels: GUI, enhancement

#3044 Description fix and some PeerTube fixes
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, peertube, youtube

#2959 mp4 muxer fix
  app/src/main/java/org/schabi/newpipe/streams/DataReader.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
Labels: bug, downloader

#2865 Fix wrong lang code of Chinese,and clean up useless strings.xml
  app/src/main/res/values-cmn/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/settings_keys.xml
Labels: localisation / translation

#2938 Spelling: Language reworked 2
  app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#3102 Fix initial brightness value
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
Labels: bug, player

#3117 fixup for #3081
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
Labels: bug, downloader

#3098 Multiple localization fixes
  app/.gitignore
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/res/layout-land/activity_player_queue_control.xml
  app/src/main/res/layout-large-land/activity_main_player.xml
  app/src/main/res/layout/activity_main_player.xml
  app/src/main/res/layout/activity_player_queue_control.xml
  app/src/main/res/layout/player_popup.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: bug, localisation / translation

#3043 Save and restore whether pitch and tempo are unhooked or not
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
Labels: player

#2967 Support display cutout
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/res/values-v28/styles.xml
  app/src/main/res/values/styles.xml
Labels: player

#3154 Round at one place for Localization.shortCount()
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: bug
