Repository TeamNewPipe/NewPipe, pull requests merged in 2020-09, with the labels that each got.

#4155 Skipping interception of some gestures
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
Labels: bug, player

#4127 Restore license pop-up when orientation changes
  app/src/main/java/org/schabi/newpipe/about/License.java
  app/src/main/java/org/schabi/newpipe/about/LicenseFragment.java
Labels: GUI, bug

#4038 Remember last selected media type for downloads.
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/res/values/settings_keys.xml
Labels: downloader

#4223 Small fixes of issues with brightness, background playback, gestures
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
Labels: bug, player

#4154 Prevent jumping of the player and wrong padding on devices with cutout
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: bug, player

#3794 Fixes crash when a file is deleted then redownloaded
  app/src/main/java/us/shandian/giga/io/StoredFileHelper.java
Labels: bug, downloader

#4029 Improve search suggestion experience when remote ones can't be fetched
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
Labels: bug

#4275 change default quality
  app/src/main/res/values/settings_keys.xml
Labels: enhancement, player

#4246 Disabled preloading when switching streams
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
Labels: player

#3178 Notification Improvements
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/NotificationConstants.java
  app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
  app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
  app/src/main/java/org/schabi/newpipe/player/playback/PlaybackListener.java
  app/src/main/java/org/schabi/newpipe/settings/BasePreferenceFragment.java
  app/src/main/java/org/schabi/newpipe/settings/NotificationSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
  app/src/main/res/drawable-hdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-hdpi/ic_close_white_24dp_png.png
  app/src/main/res/drawable-hdpi/ic_hourglass_top_white_24dp_png.png
  app/src/main/res/drawable-hdpi/ic_replay_white_24dp.png
  app/src/main/res/drawable-hdpi/ic_replay_white_24dp_png.png
  app/src/main/res/drawable-mdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_close_white_24dp_png.png
  app/src/main/res/drawable-mdpi/ic_hourglass_top_white_24dp_png.png
  app/src/main/res/drawable-mdpi/ic_replay_white_24dp.png
  app/src/main/res/drawable-mdpi/ic_replay_white_24dp_png.png
  app/src/main/res/drawable-xhdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_close_white_24dp_png.png
  app/src/main/res/drawable-xhdpi/ic_hourglass_top_white_24dp_png.png
  app/src/main/res/drawable-xhdpi/ic_replay_white_24dp.png
  app/src/main/res/drawable-xhdpi/ic_replay_white_24dp_png.png
  app/src/main/res/drawable-xxhdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_close_white_24dp_png.png
  app/src/main/res/drawable-xxhdpi/ic_hourglass_top_white_24dp_png.png
  app/src/main/res/drawable-xxhdpi/ic_replay_white_24dp.png
  app/src/main/res/drawable-xxhdpi/ic_replay_white_24dp_png.png
  app/src/main/res/drawable-xxxhdpi/ic_close_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_close_white_24dp_png.png
  app/src/main/res/drawable-xxxhdpi/ic_hourglass_top_white_24dp_png.png
  app/src/main/res/drawable-xxxhdpi/ic_replay_white_24dp.png
  app/src/main/res/drawable-xxxhdpi/ic_replay_white_24dp_png.png
  app/src/main/res/drawable/ic_close_white_24dp.xml
  app/src/main/res/drawable/ic_hourglass_top_white_24dp.xml
  app/src/main/res/drawable/ic_replay_white_24dp.xml
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/list_radio_icon_item.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/layout/player_notification.xml
  app/src/main/res/layout/player_notification_expanded.xml
  app/src/main/res/layout/player_popup_close_overlay.xml
  app/src/main/res/layout/related_streams_header.xml
  app/src/main/res/layout/settings_notification.xml
  app/src/main/res/layout/settings_notification_action.xml
  app/src/main/res/layout/single_choice_dialog_view.xml
  app/src/main/res/layout/toolbar_search_layout.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/appearance_settings.xml
  app/src/main/res/xml/main_settings.xml
  app/src/main/res/xml/video_audio_settings.xml
Labels: enhancement

#4259 Add settings migration, remove "Detail page" option from share dialog and minimize to background by default
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/report/UserAction.java
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
  app/src/main/res/values/settings_keys.xml
Labels: player

#4272 Small fixes of issues with old devices support, brightness, etc
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/java/org/schabi/newpipe/views/CustomCollapsingToolbarLayout.java
  app/src/main/java/org/schabi/newpipe/views/ExpandableSurfaceView.java
  app/src/main/java/org/schabi/newpipe/views/FocusAwareCoordinator.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/values-v29/themes.xml
  app/src/main/res/values/styles.xml
Labels: bug, player

#4315 String improvements
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#4340 Small adjustments to notification settings layout
  app/src/main/res/layout/settings_notification.xml
  app/src/main/res/layout/settings_notification_action.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-ckb/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: GUI

#4353 Prevent tapping behind queue in main player
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/player.xml
Labels: player
