Repository TeamNewPipe/NewPipe, pull requests merged in 2020-08, with the labels that each got.

#3944 Improve playlist header layout: align with info items
  app/src/main/res/layout/local_playlist_header.xml
  app/src/main/res/layout/playlist_header.xml
Labels: GUI

#3892 Fix crash when opening video in local playlist tab
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Labels: bug

#4050 Reduce redundancy in "Remeber popup size and position" setting
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#3948 Add basic resize functionality
  app/src/main/AndroidManifest.xml
Labels: enhancement

#4115 Remove timestamp from url when sharing a live stream
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
Labels: player

#4130 [regression] Close player in onPlaybackShutdown()
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
Labels: ASAP, bug, player

#4134 Set bottom padding of the main fragment when the mini player is visible
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: GUI, bug
