Repository TeamNewPipe/NewPipe, pull requests merged in 2020-12, with the labels that each got.

#5067 Add a workaround for a possible null offset ID.
  app/src/main/java/org/schabi/newpipe/ktx/OffsetDateTime.kt
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/test/java/org/schabi/newpipe/ktx/OffsetDateTimeToCalendarTest.kt
Labels: bug

#3243 Show radio icon as uploader avatar in Youtube mixes
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/test/java/org/schabi/newpipe/ktx/OffsetDateTimeToCalendarTest.kt
Labels: GUI, enhancement

#5215 Use user agent of DownloaderImpl also in ReCapthaActivity
  app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
Labels: privacy & data protection

#5228 Remove timestamp from share url for all services except youtube
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
Labels: bug, multiservice

#4754 Display meta info about search query, stream creator or topic
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: GUI, enhancement

#5259 Fix queue display in ServicePlayerActivity.
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
Labels: bug

#5258 [media.ccc.de] Fix service color
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/res/values-v21/styles_services.xml
  app/src/main/res/values/colors_services.xml
  app/src/main/res/values/styles_services.xml
Labels: GUI, bug, mediaCCC

#5286 [media.ccc.de] Add "live" kiosk
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
  app/src/main/res/drawable/ic_live_tv_black_24dp.xml
  app/src/main/res/drawable/ic_live_tv_white_24dp.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, media.ccc.de

#5251 [media.ccc.de] Add "recent" kiosk
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
  app/src/main/res/values/strings.xml
Labels: enhancement, media.ccc.de

#5317 Fix urls with timestamps not being played
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
Labels: bug, player
