Repository TeamNewPipe/NewPipe, pull requests merged in 2020-03, with the labels that each got.

#3046 Fix bug causing crashes when sharing a downloaded file.
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
Labels: bug, downloader

#3165 Mute button
  app/src/main/java/org/schabi/newpipe/player/BackgroundPlayer.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/drawable/ic_volume_off_gray_24dp.xml
  app/src/main/res/layout-large-land/activity_main_player.xml
  app/src/main/res/layout/activity_main_player.xml
  app/src/main/res/menu/menu_play_queue.xml
  app/src/main/res/values/strings.xml
Labels: player

#3197 Fix bug in main screen tabs state management
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
Labels: ASAP, GUI, bug

#3133 Change app id based on current git branch
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: meta

#3224 Fix captions overtaking mute button
  app/src/main/res/layout-large-land/activity_main_player.xml
  app/src/main/res/layout/activity_main_player.xml
Labels: player

#3177 Accept music.youtube.com in manifest
  app/src/main/AndroidManifest.xml
Labels: youtube

#3195 Fix seek duration not showing
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+ast/strings.xml
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ku/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: localisation / translation

#3225 Change share title to differentiate multiple builds
  app/build.gradle
  app/src/main/res/values/strings.xml
Labels: enhancement

#3090 Links support for mediaccc and shortened invidious
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: mediaCCC

#3132 Updating issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#3220 fix for #3204
  app/src/main/java/org/schabi/newpipe/streams/WebMReader.java
  app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
Labels: bug, downloader

#3193 Remove search icon in search mode. Issue: #3183
  app/src/main/res/layout/toolbar_search_layout.xml
Labels: GUI

#3252 Change mute button color for more visibility
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
  app/src/main/res/drawable/ic_volume_up_black_24dp.xml
  app/src/main/res/drawable/ic_volume_up_white_24dp.xml
  app/src/main/res/layout-large-land/activity_main_player.xml
  app/src/main/res/layout/activity_main_player.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: player

#3273 fix #2790
  app/src/main/java/us/shandian/giga/get/DownloadRunnable.java
Labels: bug, downloader

#3281 Temporary fix for main screen menu visibility
  app/src/main/java/androidx/fragment/app/FragmentStatePagerAdapterMenuWorkaround.java
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
Labels: ASAP, GUI, bug

#3278 Fix url parsing from shared content
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/util/urlfinder/PatternsCompat.java
  app/src/main/java/org/schabi/newpipe/util/urlfinder/UrlFinder.kt
  app/src/test/java/org/schabi/newpipe/util/urlfinder/UrlFinderTest.kt
Labels: bug

#3279 Handle content not available exception more comprehensively
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Labels: ASAP, bug

#3292 Fix UI crash in Settings, Content (chinese language)
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
Labels: bug, localisation / translation

#3289 add upload date on stream grid items
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamGridInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
  app/src/main/res/layout/list_stream_grid_item.xml
Labels: GUI

#3307 Hotfix for the latest database migration
  app/src/androidTest/java/org/schabi/newpipe/database/AppDatabaseTest.kt
  app/src/main/java/org/schabi/newpipe/database/Migrations.java
Labels: ASAP, bug
