Repository TeamNewPipe/NewPipe, pull requests merged in 2020-11, with the labels that each got.

#4587 Separate player gesture logic and UI
  app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/event/DisplayPortion.kt
  app/src/main/java/org/schabi/newpipe/player/event/DoubleTapListener.kt
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
Labels: player

#4790 Update readme and add custom repo info
  README.md
Labels: meta

#4759 Change YouTube subscription import instructions to Google takeout
  app/build.gradle
  app/src/main/res/values/strings.xml
Labels: bug, youtube

#4749 [Translation]Added Santali language
  app/src/main/res/values/settings_keys.xml
Labels: localisation / translation

#4555 Fix NullPointerException in queue handling
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
Labels: bug

#4771 Fix playlist select dialog and do some refactoring
  app/src/main/java/org/schabi/newpipe/settings/SelectPlaylistFragment.java
Labels: bug

#4921 Call DateWrapper's offsetDateTime() instead of date().
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: bug

#4937 Fix respecting brightness-volume-gesture settings
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
Labels: bug, player

#4948 Fix crash on startup when there is no internet connection
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
Labels: ASAP, bug

#4969 [PeerTube] update instances list
  app/src/main/AndroidManifest.xml
Labels: enhancement, peertube

#4318 Contributing guidelines reworked
  .github/CONTRIBUTING.md
Labels: meta
