Repository TeamNewPipe/NewPipe, pull requests merged in 2020-04, with the labels that each got.

#3322 Fix mute button causing crashes on API 19
  app/src/main/java/org/schabi/newpipe/player/ServicePlayerActivity.java
Labels: ASAP, GUI, bug

#3259 Improvements for the drawer header layout
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/res/drawable-hdpi/ic_arrow_down_white.png
  app/src/main/res/drawable-hdpi/ic_arrow_up_white.png
  app/src/main/res/drawable-mdpi/ic_arrow_down_white.png
  app/src/main/res/drawable-mdpi/ic_arrow_up_white.png
  app/src/main/res/drawable-xhdpi/ic_arrow_down_white.png
  app/src/main/res/drawable-xhdpi/ic_arrow_up_white.png
  app/src/main/res/drawable-xxhdpi/ic_arrow_down_white.png
  app/src/main/res/drawable-xxhdpi/ic_arrow_up_white.png
  app/src/main/res/drawable/drawer_header_bottom_background.xml
  app/src/main/res/drawable/ic_arrow_drop_down_white_24dp.xml
  app/src/main/res/drawable/ic_arrow_drop_up_white_24dp.xml
  app/src/main/res/layout-v21/drawer_header.xml
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/layout/drawer_layout.xml
  app/src/main/res/values-v21/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: GUI

#3325 Integer overflow fixes in downloader
  app/src/main/java/org/schabi/newpipe/streams/DataReader.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4DashReader.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
  app/src/main/java/us/shandian/giga/io/ChunkFileInputStream.java
  app/src/main/java/us/shandian/giga/io/CircularFileWriter.java
Labels: downloader

#3374 Fix visibility of group sort button in the subscriptions fragment
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderWithMenuItem.kt
Labels: GUI, bug

#3300 handle ContentNotSupportedException
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/res/layout/fragment_channel.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, requires extractor change

#3240 YouTube Music search stuff
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/PlaylistMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, youtube

#3075 Better popup resizing with pinch gestures
  app/src/main/java/org/schabi/newpipe/player/PopupVideoPlayer.java
Labels: player

#3294 Fix detection of network related exceptions
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/services/BaseImportExportService.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
  app/src/main/java/org/schabi/newpipe/util/ExceptionUtils.kt
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/test/java/org/schabi/newpipe/util/ExceptionUtilsTest.kt
Labels: ASAP, bug

#3414 Fix ReCaptcha Activity for another type of recaptcha page
  app/src/debug/java/org/schabi/newpipe/DebugApp.java
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/ReCaptchaActivity.java
  app/src/main/res/values/settings_keys.xml
Labels: ASAP, bug, youtube

#3483 Better detection of TV devices
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/java/org/schabi/newpipe/util/AndroidTvUtils.java
Labels: ASAP, Android TV, bug
