Repository TeamNewPipe/NewPipe, pull requests merged in 2021-09, with the labels that each got.

#5459 Add option to directly open fullscreen when the main player starts
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/video_audio_settings.xml
Labels: enhancement, player

#7055 Added night variant for splash_background.xml
  app/src/main/res/drawable-night-v23/splash_background.xml
  app/src/main/res/drawable-night/splash_background.xml
Labels: GUI

#7071 Change player progress bar update from 500 ms to 1 s
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: player

#7085 Fixed the navbar color for darkmode
  app/src/main/res/values-night-v21/styles.xml
Labels: bug, GUI

#7056 Fix handling exception in `playOnPopup` and toggle description tab
  app/src/main/java/org/schabi/newpipe/BaseFragment.java
  app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
  app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
Labels: bug

#7068 Fixed restarting not working properly
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: bug

#6974 Update Android Gradle Plugin to version 7.0.2
  .github/workflows/ci.yml
  build.gradle
Labels: meta

#7098 Allow passing in package suffix for release builds through CLI param
  app/build.gradle
  doc/gradle.md
Labels: meta

#6872 Added a play next button to the long press menu
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/res/values/strings.xml
Labels: enhancement, GUI, player

#7042 Make all buttons in player have selectable item background borderless
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/player.xml
Labels: GUI, player

#7156 Remove deprecated preferenceTheme style attribute
  app/src/main/res/values/styles.xml
Labels: codequality

#7152 Regenerate some drawables to their latest design
  app/src/main/java/org/schabi/newpipe/local/subscription/FeedGroupIcon.kt
  app/src/main/res/drawable-night/ic_campaign.xml
  app/src/main/res/drawable-night/ic_drag_handle.xml
  app/src/main/res/drawable-night/ic_edit.xml
  app/src/main/res/drawable-night/ic_expand_less.xml
  app/src/main/res/drawable-night/ic_import_export.xml
  app/src/main/res/drawable-night/ic_info_outline.xml
  app/src/main/res/drawable-night/ic_megaphone.xml
  app/src/main/res/drawable-night/ic_motorcycle.xml
  app/src/main/res/drawable-night/ic_palette.xml
  app/src/main/res/drawable-night/ic_playlist_add.xml
  app/src/main/res/drawable-night/ic_playlist_add_check.xml
  app/src/main/res/drawable-night/ic_search_add.xml
  app/src/main/res/drawable-night/ic_settings.xml
  app/src/main/res/drawable-night/ic_thumb_down.xml
  app/src/main/res/drawable-night/ic_thumb_up.xml
  app/src/main/res/drawable-night/ic_watch_later.xml
  app/src/main/res/drawable/ic_campaign.xml
  app/src/main/res/drawable/ic_drag_handle.xml
  app/src/main/res/drawable/ic_info_outline.xml
  app/src/main/res/drawable/ic_megaphone.xml
  app/src/main/res/drawable/ic_motorcycle.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_palette.xml
  app/src/main/res/drawable/ic_playlist_add.xml
  app/src/main/res/drawable/ic_playlist_add_check.xml
  app/src/main/res/drawable/ic_playlist_play.xml
  app/src/main/res/drawable/ic_previous.xml
  app/src/main/res/drawable/ic_search_add.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_thumb_down.xml
  app/src/main/res/drawable/ic_thumb_up.xml
  app/src/main/res/drawable/ic_watch_later.xml
Labels: codequality

#7178 Disable media tunneling on RealtekATV
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: bug, player, device/software specific

#7181 Add YouTube shorts path prefix to intent filter
  app/src/main/AndroidManifest.xml
Labels: enhancement, youtube
