Repository TeamNewPipe/NewPipe, pull requests merged in 2021-12, with the labels that each got.

#7498 Updated/Fixed "Get it on F-Droid"
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  README.tr.md
Labels: bug, meta

#7497 Disable media tunneling on Philips QM16XE
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: player, device/software specific

#7481 Add FSFE-Tube PeerTube instance
  app/src/main/AndroidManifest.xml
Labels: enhancement, peertube

#7491 Fix order of local search results
  app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt
  app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
  app/src/androidTest/java/org/schabi/newpipe/testUtil/TestDatabase.kt
  app/src/main/java/org/schabi/newpipe/database/history/dao/SearchHistoryDAO.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
Labels: bug

#7482 Unify error reporting and add error notification
  app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/error/AcraReportSender.java
  app/src/main/java/org/schabi/newpipe/error/EnsureExceptionSerializable.java
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt
  app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
  app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionsImportFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/BaseImportExportService.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/playererror/PlayerErrorHandler.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectChannelFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectKioskFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/debug_settings.xml
Labels: enhancement

#7452 Show an alert-dialog when no appropriate file-manager was found
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionsImportFragment.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/streams/io/NoFileManagerSafeGuard.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
  app/src/main/res/values/strings.xml
Labels: bug

#7499 Update a bunch of libraries
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: codequality

#7451 Respect cutouts when playing in MultiWindow
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: enhancement, GUI, player

#7552 Readd sonar CI job
  .github/workflows/ci.yml
Labels: CI

#7555 Remove/Revert MediaParser support (Android 11+) due to bugs
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
Labels: bug, youtube, player, device/software specific

#7556 Fixes hashtags that use non-English characters.
  app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java
Labels: bug

#7562 Small improvements to code quality and readability
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/settings/BasePreferenceFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
  app/src/main/java/us/shandian/giga/io/FileStreamSAF.java
Labels: codequality

#7577 Added ability to see pinned comment
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsInfoItemHolder.java
  app/src/main/res/drawable-night/ic_pin.xml
  app/src/main/res/drawable/ic_pin.xml
  app/src/main/res/layout/list_comments_item.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, GUI

#7589 Updated NewPipeExtractor
  app/build.gradle
Labels: bug, youtube

#7582 Fixes view of sub-channel icon when not in use
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, GUI, peertube

#7568 Add Already playing in background toast
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/values/strings.xml
Labels: enhancement
