Repository TeamNewPipe/NewPipe, pull requests merged in 2021-07, with the labels that each got.

#6570 Fix NPE when connecting via BT
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#6545 [Localization]Fix Simplified Chinese Plural
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
Labels: bug, localisation / translation

#6593 Add question template
  .github/ISSUE_TEMPLATE/question.md
Labels: meta

#6622 Fix crash when using repeatButtonin tablet layout
  app/src/main/res/layout-large-land/player.xml
Labels: bug, player

#6623 Fix APK testing section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#6639 Fix crash when refreshing feed after importing database or subscriptions
  app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: bug

#6538 Bump gradle
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: codequality

#6540 Update some libraries
  app/build.gradle
Labels: codequality

#6560 Specify emulator-build version in CI job
  .github/workflows/ci.yml
Labels: bug

#6616 Made the thumbnail in the minimized player visible again
  app/src/main/res/layout/fragment_video_detail.xml
Labels: bug, player

#6463 Improved metadata layout, better tags accessibility
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/res/layout/chip.xml
  app/src/main/res/layout/item_metadata.xml
  app/src/main/res/layout/item_metadata_tags.xml
Labels: GUI

#6566 Convert PlayerHolder to Singleton; cleanup in VideoDetailFragment; Player/MainPlayer do not call onDestroy() directly
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Labels: codequality

#6531 Remove option to immediately commit pref changes on import
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
Labels: codequality

#6503 Prevent error msg: 'Unrecoverable player error occurred' while playin…
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/playback/SurfaceHolderCallback.java
Labels: bug, player

#6678 Remove api level 29 from android ci tests
  .github/workflows/ci.yml
Labels: codequality

#6637 Use GestureDetectorCompat.
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: codequality, player

#6483 Added comments disabled functionallity
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/res/layout/fragment_comments.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, youtube

#5531 Add instrumented tests for LocalPlaylistManager.createPlaylist
  app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
  app/src/androidTest/java/org/schabi/newpipe/testUtil/TrampolineSchedulerRule.kt
Labels: codequality

#6536 More onActivityResult deprecation fixes
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
Labels: codequality

#6456 Apply theme to switches
  app/src/main/res/layout/related_items_header.xml
  app/src/main/res/values-v21/styles_services.xml
  app/src/main/res/values/styles.xml
Labels: GUI, bandcamp, multiservice

#6434 Player seekbar thumbnail preview
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHelper.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHolder.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SyncImageLoadingListener.java
  app/src/main/java/org/schabi/newpipe/util/ImageDisplayConstants.java
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/video_audio_settings.xml
Labels: enhancement, player

#6675 Use Kotlin methods in LicenseFragment.
  app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
Labels: codequality

#6701 Dismiss download dialog correctly
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Labels: GUI, bug

#6705 Fix grid span count calculation
  app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
Labels: GUI, bug

#6715 Readd api level 29 to android CI tests
  .github/workflows/ci.yml
Labels: CI

#6712 Fix duplicate items in queue causing endless buffering
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java
  app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueItemTest.java
  app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
Labels: bug

#6721 Delete pending missions with invalid storage
  app/src/main/java/us/shandian/giga/service/DownloadManager.java
Labels: bug, downloader

#6771 Fixed the ToolbarSearchTheme
  app/src/main/res/values/styles_misc.xml
Labels: GUI, bug

#6782 Fix deprecated fill_parent attributes
  app/src/main/res/layout/activity_error.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/missions.xml
Labels: codequality

#6778 Fix NullPointerException when checking if storage exists
  app/src/main/java/org/schabi/newpipe/streams/io/StoredFileHelper.java
  app/src/main/java/us/shandian/giga/get/DownloadMission.java
Labels: bug, downloader
