Repository TeamNewPipe/NewPipe, pull requests merged in 2021-01, with the labels that each got.

#5221 Dynamically get package name
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
Labels: bug, feed, notification, player

#5250 Change "Export" to "Import" in Korean Readme instructions
  README.ko.md
Labels: localisation / translation

#5337 Disable sending metrics to Google when using Android System WebView
  app/src/main/AndroidManifest.xml
Labels: privacy & data protection

#5331 In Fullscreen playback, toggle play/pause with hardware space button
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
Labels: player

#5376 [localization] Fixes Somali language name
  app/src/main/res/values/settings_keys.xml
Labels: localisation / translation

#5257 [peertube] implement sepia search
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
Labels: enhancement, peertube

#5383 Created Somali Readme
  README.so.md
Labels: enhancement, localisation / translation, meta

#5310 add list item to play video on kodi
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/util/KoreUtil.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Labels: GUI

#5371 Merge player classes into a single one
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/BackgroundPlayerActivity.java
  app/src/main/java/org/schabi/newpipe/player/BasePlayer.java
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/PlayerServiceBinder.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayer.java
  app/src/main/java/org/schabi/newpipe/player/VideoPlayerImpl.java
  app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceExtendedEventListener.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionCallback.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueueNavigator.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueuePlaybackController.java
  app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/layout-land/activity_player_queue_control.xml
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/activity_player_queue_control.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/menu/menu_play_queue.xml
  app/src/main/res/values/settings_keys.xml
  checkstyle-suppressions.xml
Labels: player

#4939 VideoDetailFragment: Don't exit fullscreen on rotation in tablet UI
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, player

#5397 Created Brazilian Portuguese Readme
  README.ko.md
  README.md
  README.pt.br.md
  README.so.md
Labels: localisation / translation

#5274 Add stream segments to player controls
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentAdapter.kt
  app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/res/drawable/ic_format_list_numbered_white_24.xml
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/item_stream_segment.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/values/strings.xml
Labels: GUI, enhancement, player

#5187 Share improvements + fix crash when no default browser is set on some devices
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
  app/src/main/java/org/schabi/newpipe/ImageDownloader.java
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/player/MainPlayer.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
  app/src/main/java/org/schabi/newpipe/report/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/settings/BasePreferenceFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectChannelFragment.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/TabsManager.java
  app/src/main/java/org/schabi/newpipe/util/CommentTextOnTouchListener.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/FilenameUtils.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/PeertubeHelper.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/java/org/schabi/newpipe/util/TextLinkifier.java
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
  app/src/main/java/org/schabi/newpipe/views/CustomCollapsingToolbarLayout.java
  app/src/main/java/org/schabi/newpipe/views/ExpandableSurfaceView.java
  app/src/main/java/org/schabi/newpipe/views/FocusAwareCoordinator.java
  app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
  checkstyle-suppressions.xml
Labels: bug

#5438 Use view binding in VideoDetailFragment.
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: codequality

#4534 Add a secondary control panel to video detail fragment
  app/src/main/java/org/schabi/newpipe/BaseFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedVideosFragment.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/res/drawable/dot_default.xml
  app/src/main/res/drawable/dot_selected.xml
  app/src/main/res/drawable/ic_art_track_white_24dp.xml
  app/src/main/res/drawable/ic_comment_white_24dp.xml
  app/src/main/res/drawable/ic_description_white_24dp.xml
  app/src/main/res/drawable/tab_selector.xml
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_description.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: enhancement

#5429 Fix crash when no browser is present and use an ACTION_CHOOSER intent in the app update notification
  app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
  app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#5463 Fix number being shown instead of corresponding string resorce in feed
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Labels: bug

#5439 Update README.so.md to sync with the English one
  README.so.md
Labels: localisation / translation

#5458 Fix popup closing x button animation
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
Labels: bug, player

#5468 Add Japanese translation of README
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.so.md
Labels: localisation / translation

#5480 update invidious instances list
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: ASAP, youtube

#5502 Fix minimize on app switch always opens popup
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
Labels: bug, player

#5501 Add README.ro.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
Labels: localisation / translation

#5503 Set all default settings at the beginning
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
Labels: codequality

#5465 Re-add APK testing section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#5466 Fix some things in ShareUtils file and do little improvements
  app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
Labels: bug, codequality

#5474 Respect expires header when checking for new versions
  app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
  app/src/main/java/org/schabi/newpipe/NewVersionManager.kt
  app/src/main/res/values/settings_keys.xml
  app/src/test/java/org/schabi/newpipe/NewVersionManagerTest.kt
Labels: bug, privacy & data protection
