Repository TeamNewPipe/NewPipe, pull requests merged in 2021-02, with the labels that each got.

#5464 Fix channel subscribe button causing crash on closing
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Labels: bug

#5564 Release 0.20.9
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/963.txt
Labels: bug, youtube

#5563 Fix tab layout visibility with age restricted videos
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: GUI, bug

#5544 Remove License#contentUri
  app/src/main/java/org/schabi/newpipe/about/License.kt
Labels: codequality

#5543 Remove unnecessary concat with empty string
  app/src/main/java/org/schabi/newpipe/ktx/View.kt
Labels: codequality
