Repository TeamNewPipe/NewPipe, pull requests merged in 2021-10, with the labels that each got.

#7177 Expand minimized player buttons clickable area
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: enhancement, GUI

#7184 Update READMEs
  README.es.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  README.tr.md
Labels: meta, localisation / translation

#7176 Fixed seekbar not completed after video end
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#6824 Swap seekbar position with player buttons in Queue screen
  app/src/main/res/layout/activity_player_queue_control.xml
Labels: GUI

#7165 Simplify the feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: meta

#7188 Update README.es
  README.es.md
Labels: meta, localisation / translation

#6642 Add Tubus (Invidious) and EduVid (PeerTube)
  app/src/main/AndroidManifest.xml
Labels: enhancement, youtube, peertube
