Repository TeamNewPipe/NewPipe, pull requests merged in 2021-08, with the labels that each got.

#6773 Add ability to mark an item as played
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/res/values/strings.xml
Labels: enhancement, feed

#6741 Show hearts in comments
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsInfoItemHolder.java
  app/src/main/res/drawable-night/ic_heart.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/layout/list_comments_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: GUI, enhancement

#6633 Use NotificationChannelCompat.
  app/src/main/java/org/schabi/newpipe/App.java
Labels: codequality

#6550 Disable feed click events while refresh overlay is shown
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Labels: bug, feed

#6792 Update extractor, thus including throttling fixes
  app/build.gradle
Labels: bug, youtube

#6789 Ignore paths unrelated to builds in CI
  .github/workflows/ci.yml
Labels: CI, enhancement

#6809 Allow manual execution of ci workflow
  .github/workflows/ci.yml
Labels: CI, enhancement

#6847 Play queue theme
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
Labels: GUI, bug

#6814 Fix channel item span count for SubscriptionFragment
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
Labels: GUI, bug

#6858 Add gradle parameter to skip formatKtLint and use in CI
  .github/workflows/ci.yml
  app/build.gradle
Labels: CI

#6956 Only show "mark as watched" when watch history is enabled
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Labels: bug, feed

#6952 Added wrapping settings titles to the next line
  app/src/main/res/xml/appearance_settings.xml
  app/src/main/res/xml/content_settings.xml
  app/src/main/res/xml/debug_settings.xml
  app/src/main/res/xml/download_settings.xml
  app/src/main/res/xml/history_settings.xml
  app/src/main/res/xml/notification_settings.xml
  app/src/main/res/xml/update_settings.xml
  app/src/main/res/xml/video_audio_settings.xml
Labels: bug, GUI

#6848 Use custom cancel string everywhere
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/res/layout/dialog_feed_group_create.xml
Labels: bug, localisation / translation

#6244 changed dark theme colors to darker variant
  app/src/main/res/values/colors_services.xml
Labels: enhancement, GUI

#5928 Replace UniversalImageLoader with Picasso
  app/build.gradle
  app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/BaseFragment.java
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
  app/src/main/java/org/schabi/newpipe/ImageDownloader.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoItemBuilder.java
  app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt
  app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/PlaylistMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/LocalItemBuilder.java
  app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerSubscriptionItem.kt
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItemBuilder.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHolder.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SyncImageLoadingListener.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectChannelFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/util/ImageDisplayConstants.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/debug_settings.xml
Labels: bug, enhancement, notification, codequality

#6942 Add no-response workflow
  .github/workflows/no-response.yml
Labels: meta

#6919 Add Show Channel Details where it's missing
  app/schemas/org.schabi.newpipe.database.AppDatabase/4.json
  app/src/androidTest/java/org/schabi/newpipe/database/AppDatabaseTest.kt
  app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
  app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java
  app/src/main/java/org/schabi/newpipe/database/AppDatabase.java
  app/src/main/java/org/schabi/newpipe/database/Migrations.java
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt
  app/src/main/java/org/schabi/newpipe/database/stream/StreamStatisticsEntry.kt
  app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamDAO.kt
  app/src/main/java/org/schabi/newpipe/database/stream/model/StreamEntity.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#3546 Allow choosing which types of search suggestions to show
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionItem.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: enhancement, GUI

#6917 Change "not available" image from PNG to vector format
  app/src/main/res/drawable-nodpi/not_available_monkey.png
  app/src/main/res/drawable/not_available_monkey.xml
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: enhancement

#6515 Use ExoPlayer default values for buffers
  app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
Labels: bug, player

#7014 Fixed double tapping the replay button
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#6634 Use PackageInfoCompat.getSignatures().
  app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
Labels: codequality

#6986 Fix build problems and updated kotlin
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/about/License.kt
  app/src/main/java/org/schabi/newpipe/about/SoftwareComponent.kt
  app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/util/SavedState.kt
  app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.kt
  build.gradle
Labels: meta

#6985 Set ``KeyProgressIncrement`` manually / Fix long seekbar jumps when using a DPad
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: enhancement, player, Android TV

#7002 Using integrated cache in ``actions/setup-java``
  .github/workflows/ci.yml
Labels: CI

#6882 Add support for CSV+ZIP subscriptions (Google Takeout)
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
  app/src/main/res/values/strings.xml
Labels: bug, ASAP, youtube

#6965 Add how to remove tab from main page text
  app/src/main/res/layout/fragment_choose_tabs.xml
  app/src/main/res/values/strings.xml
Labels: GUI

#6955 Show popup menu when long pressing in play queue (Full screen player)
  app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/res/menu/menu_play_queue_item.xml
Labels: bug, player

#6993 Close audio effect control session properly
  app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
Labels: bug, player

#7004 Reworked the ErrorPanel
  app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
  app/src/main/res/layout/error_panel.xml
Labels: bug, GUI
