Repository TeamNewPipe/NewPipe, pull requests merged in 2021-05, with the labels that each got.

#6219 Added Turkish README
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  README.tr.md
Labels: localisation / translation

#6206 Update ExoPlayer to 2.13.3
  app/build.gradle
Labels: player

#5997 Do not set reCaptcha cookie when there is no cookie stored
  app/src/main/java/org/schabi/newpipe/App.java
Labels: privacy & data protection

#6189 Fix some warnings
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/PickerIconItem.kt
  app/src/main/res/values-kmr/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-sr/strings.xml
Labels: codequality

#6238 Fix: fragmentSize is below the minimum
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
Labels: player

#6152 Use Animator.addListener() extension.
  app/src/main/java/org/schabi/newpipe/ktx/TextView.kt
  app/src/main/java/org/schabi/newpipe/ktx/View.kt
Labels: codequality

#5994 Add NoLoginRequired in Readme file
  README.md
Labels: meta

#5671 Downloader: Deleter: Dismiss previous Snackbars
  app/src/main/java/us/shandian/giga/ui/common/Deleter.java
Labels: downloader, enhancement

#6127 Fix trying to delete object not in list
  app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
  checkstyle-suppressions.xml
Labels: bug

#6288 Add debug option to disable media tunneling
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/debug_settings.xml
Labels: player

#6303 Add No Login Required translation for Romanian
  README.ro.md
Labels: localisation / translation, meta

#6294 Downgrade ExoPlayer to 2.12
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
  app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
Labels: bug, player

#6312 Fix ErrorActivity actionbar back button not working
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
Labels: GUI, bug

#6308 Make some minor changes
  app/src/main/java/org/schabi/newpipe/ktx/Throwable.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/HeaderItem.kt
  app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
Labels: codequality

#6317 Excluding forgotten parts of the original raw
  README.pt_BR.md
Labels: localisation / translation, meta

#6319 Save backup import/export location for future import/exports
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/FilePathUtils.java
  app/src/main/res/values/settings_keys.xml
  app/src/test/java/org/schabi/newpipe/util/FilePathHelperTest.java
Labels: enhancement

#6307 Add support for PeerTube HLS streams
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, peertube, player

#6360 Use AdoptOpenJDK instead of Zulu in GitHub actions
  .github/workflows/ci.yml
Labels: codequality

#6345 Test and clean up PlayQueue
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
  app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
Labels: codequality

#6384 Update Matrix link of NewPipe IRC from Freenode to Libera.chat
  .github/ISSUE_TEMPLATE/config.yml
Labels: meta

#6373 Improve Bandcamp intent filters
  app/src/main/AndroidManifest.xml
Labels: bandcamp, bug

#6387 Fix empty fragment text not centered when text longer than one line
  app/src/main/res/layout/main_bg.xml
Labels: GUI, bug

#6353 Fix unwanted rich text formatting when pasting
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
Labels: GUI, bug

#6118 Error handling in subscribe() in DownloadDialog
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Labels: bug, downloader

#6393 Change IRC chat button link in READMEs
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  README.tr.md
Labels: meta
