Repository TeamNewPipe/NewPipe, pull requests merged in 2021-03, with the labels that each got.

#5721 Add Northern Kurdish to language selector
  app/src/main/res/values/settings_keys.xml
Labels: localisation / translation

#5718 Fix crash when reordering channel groups.
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupReorderItem.kt
Labels: GUI, bug

#5385 Better error messages for SoundCloud and YouTube unavailable contents
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: GUI, enhancement, soundcloud, youtube

#5764 Add links to Matrix and IRC chat when opening new issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: meta

#5562 Implement "pause/play" toggle on hardware keyboard space button.
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: enhancement, player

#3741 Bandcamp support
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/res/drawable-nodpi/place_holder_bandcamp.png
  app/src/main/res/values/colors_services.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles_services.xml
Labels: bandcamp, enhancement

#5818 [background player] Fix very small thumbnails
  app/src/main/res/layout/fragment_video_detail.xml
Labels: GUI, bug, player

#5841 Re-add badges to localized README's
  README.ja.md
  README.ko.md
  README.pt_BR.md
  README.ro.md
  README.so.md
Labels: localisation / translation

#5829 Spanish README.md
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
Labels: localisation / translation

#5820 Fix empty stream title in minimized player
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: GUI, bug, player

#5792 Fix last resize mode not being restored correctly
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
Labels: bug, player

#5230 Update prettytime.
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/ktx/OffsetDateTime.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedState.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/test/java/org/schabi/newpipe/ktx/OffsetDateTimeToCalendarTest.kt
  app/src/test/java/org/schabi/newpipe/util/LocalizationTest.kt
Labels: codequality, localisation / translation

#3632 Add settings to match device's theme (dark & black)
  app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/appearance_settings.xml
Labels: GUI, enhancement

#5457 Update to ExoPlayer 2.12.3
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/PlaceholderMediaSource.java
Labels: player

#5844 Sonar workflow
  .github/workflows/ci.yml
  app/build.gradle
  checkstyle.xml
Labels: meta

#5519 Add toast to inform the user that download started.
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/res/values/strings.xml
Labels: GUI

#5899 Fix settings switches are not red anymore
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
Labels: GUI, bug

#5896 Fix error panel created in onViewCreated() but disposed in onDestroy()
  app/src/main/java/org/schabi/newpipe/fragments/BaseStateFragment.java
Labels: bug

#5649 Change UA to privacy.resistFingerprinting.
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
Labels: enhancement, privacy & data protection

#5907 Update strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: ASAP, localisation / translation

#5910 Update translations
  app/src/main/res/values-fr/strings.xml
  fastlane/metadata/android/id/changelogs/63.txt
  fastlane/metadata/android/id/changelogs/64.txt
  fastlane/metadata/android/id/changelogs/953.txt
  fastlane/metadata/android/id/full_description.txt
Labels: localisation / translation

#5882 Replace FrameLayout with FragmentContainerView where applicable
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/activity_downloader.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/settings_layout.xml
Labels: codequality, enhancement

#5879 Clean up unnecessary onCreate in settings fragments
  app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/UpdateSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
Labels: codequality, enhancement

#5939 Change the old NewPipe domain to the new domain in READMEs
  README.es.md
  README.md
  README.ro.md
Labels: meta

#5851 Add channel details option to long-press menu
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/res/values/strings.xml
Labels: GUI, enhancement

#5942 Update URLs to HTTPS
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
Labels: meta

#5929 #5263: Allow the user to pause while a video is buffering
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#5360 Run Instrumented tests in CI pipeline
  .github/workflows/ci.yml
Labels: meta

#5813 Overlapping fonts #5096
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
  app/src/main/res/layout/list_channel_item.xml
  app/src/main/res/layout/list_stream_item.xml
Labels: GUI, bug

#5856 Update to ExoPlayer 2.13.2
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
  app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
  app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
  app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
Labels: player

#5944 Fix some random NullPointerExceptions
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
Labels: bug

#5935 Fix hidden icon to the left of notification actions in settings
  app/src/main/res/layout/settings_notification_action.xml
Labels: GUI, bug
