Repository TeamNewPipe/NewPipe, pull requests merged in 2021-06, with the labels that each got.

#6410 Fixed channel description textView
  app/src/main/res/layout/list_channel_item.xml
Labels: GUI, bug

#6414 Upgrade PrettyTime to 5.0.1
  app/build.gradle
Labels: localisation / translation

#6415 Change NewPipe IRC links in the contribution guidelines
  .github/CONTRIBUTING.md
Labels: meta

#6242 fix Rotation crash on „Video not available“ page (#5941)
  app/src/main/java/org/schabi/newpipe/fragments/EmptyFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug

#6309 Add "Show channel details" option in remote (non-local) playlists
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Labels: bug

#6280 Add Open in browser option to long-press menu
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Labels: GUI, enhancement

#5946 Show content metadata below the description
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/res/drawable-night/ic_select_all.xml
  app/src/main/res/drawable/ic_select_all.xml
  app/src/main/res/layout/chip.xml
  app/src/main/res/layout/fragment_description.xml
  app/src/main/res/layout/item_metadata.xml
  app/src/main/res/layout/item_metadata_tags.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, multiservice

#6402 Fix and improve setting import and export paths
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
Labels: bug

#6337 [YouTube] Fix broken likes in comments
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
Labels: bug, youtube

#6421 Fix playback speed not being updated in PlayQueueAcitvity
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
Labels: GUI, bug, player

#6429 Fix Play with Kodi button in Player always prompts to install Kore
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: bug

#6430 Localization updates and small code improvements
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/java/us/shandian/giga/io/StoredFileHelper.java
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+ast/strings.xml
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl-rBE/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-or/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelperTest.java
  fastlane/metadata/android/de/changelogs/968.txt
  fastlane/metadata/android/de/changelogs/969.txt
  fastlane/metadata/android/fr/changelogs/963.txt
  fastlane/metadata/android/fr/changelogs/967.txt
  fastlane/metadata/android/fr/changelogs/968.txt
  fastlane/metadata/android/id/changelogs/969.txt
  fastlane/metadata/android/lt/full_description.txt
  fastlane/metadata/android/lt/short_description.txt
  fastlane/metadata/android/or/short_description.txt
  fastlane/metadata/android/sk/changelogs/969.txt
  fastlane/metadata/android/sr/full_description.txt
  fastlane/metadata/android/uk/short_description.txt
  fastlane/metadata/android/zh-Hans/changelogs/66.txt
Labels: localisation / translation

#6438 Increase width of metadata text view
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/res/layout/item_metadata.xml
  app/src/main/res/layout/item_metadata_tags.xml
Labels: GUI, bug

#5876 Better error handling of terminated channels
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt
  app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/res/layout/error_panel.xml
  app/src/main/res/values/strings.xml
Labels: bug, youtube

#5462 Convert the abstract class DAOs to interfaces.
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistRemoteDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
  app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamStateDAO.java
Labels: codequality

#6346 Resolve Tabs style checks
  app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
Labels: codequality

#6444 Increase buffer for playback after rebuffer
  app/src/main/java/org/schabi/newpipe/player/helper/LoadController.java
Labels: player

#6313 Update Room to 2.3.0.
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/database/Converters.java
  app/src/main/java/org/schabi/newpipe/database/Converters.kt
Labels: codequality

#6480 Added itemsListHeaderDuration to large-hand player
  app/src/main/res/layout-large-land/player.xml
Labels: bug

#5523 Recognize timestamps and hashtags in descriptions and do some sharing fixes and improvements
  app/src/main/java/org/schabi/newpipe/CheckForNewAppVersion.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/util/CommentTextOnTouchListener.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/ShareUtils.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
  app/src/main/java/org/schabi/newpipe/util/TextLinkifier.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/KoreUtils.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/TextLinkifier.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
Labels: GUI, bug, enhancement

#6059 Adds manual tablet mode setting
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/appearance_settings.xml
Labels: GUI, enhancement

#6495 Replace the System.exit calls with getActivity.finishAffinity()
  app/src/main/java/org/schabi/newpipe/ExitActivity.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: codequality

#3371 Add ability to hide played items in a feed
  app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
  app/src/main/java/org/schabi/newpipe/database/history/dao/StreamHistoryDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistStreamEntry.kt
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
  app/src/main/java/org/schabi/newpipe/database/stream/StreamStatisticsEntry.kt
  app/src/main/java/org/schabi/newpipe/database/stream/StreamWithState.kt
  app/src/main/java/org/schabi/newpipe/database/stream/model/StreamStateEntity.java
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedState.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt
  app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamItemHolder.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/res/drawable-night/ic_visibility_off.xml
  app/src/main/res/drawable-night/ic_visibility_on.xml
  app/src/main/res/drawable/ic_visibility_off.xml
  app/src/main/res/drawable/ic_visibility_on.xml
  app/src/main/res/drawable/item_in_history_indicator_background.xml
  app/src/main/res/layout/list_stream_grid_item.xml
  app/src/main/res/layout/list_stream_item.xml
  app/src/main/res/menu/menu_feed_fragment.xml
  app/src/main/res/menu/menu_main_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: GUI, enhancement, feed

#6394 Update AndroidX Fragment to 1.3.4
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionsImportFragment.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Labels: codequality

#6528 Annotate some overridden methods and parameters as NonNull
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SelectKioskFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
Labels: codequality

#6516 Don't enable SAF on Fire TV
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: bug, device/software specific

#6556 Refactoring by Android Studio
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
Labels: codequality, enhancement

#6557 Update Invidious instances and support Piped links
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: youtube

#6482 Build instructions
  .github/CONTRIBUTING.md
  app/build.gradle
Labels: meta

#6539 Ask for screenshots/video of UI changes in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta
