Repository TeamNewPipe/NewPipe, pull requests merged in 2021-04, with the labels that each got.

#5982 Add functionality to rename Playlist Name from playlist interface
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/res/menu/menu_local_playlist.xml
Labels: enhancement

#5974 Rename related streams to related items
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/player/event/CustomBottomSheetBehavior.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/util/RelatedItemInfo.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_related_items.xml
  app/src/main/res/layout/related_items_header.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-kmr/strings.xml
  app/src/main/res/values-ku/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values-sq/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-ur/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, multiservice

#5999 Fix NullPointerException: Attempt to get length of null array in MainActivity
  app/src/main/java/org/schabi/newpipe/util/StateSaver.java
Labels: bug

#6001 Migrate rest of AlertDialogs to AppCompat
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/AddTabDialog.java
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
Labels: codequality, enhancement

#6023 Add queue time
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/res/layout/player.xml
Labels: enhancement, player

#5963 Fix display of channel details when it has no videos
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Labels: bug

#6060 Fix ic_volume_up and ic_volume_off being black
  app/src/main/res/drawable-night/ic_volume_off.xml
  app/src/main/res/drawable/ic_volume_up.xml
Labels: GUI, bug

#6051 [Bandcamp] Add Radio stream segments
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt
  app/src/main/res/layout/item_stream_segment.xml
Labels: bandcamp, enhancement

#6037 Allow installation on external storage
  app/src/main/AndroidManifest.xml
Labels: enhancement

#6109 Replaced if/else with switch in ErrorActivity
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
Labels: codequality

#6140 Update shot_10.png to include Bandcamp in the list of services
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_10.png
Labels: meta

#6161 Fix invisible buffering / loading indicator in player
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: GUI, bug, player

#6151 Fix black drawables in night themes in share dialog (RouterActivity)
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/res/drawable-night/ic_headset.xml
  app/src/main/res/drawable-night/ic_info_outline.xml
  app/src/main/res/drawable-night/ic_picture_in_picture.xml
  app/src/main/res/drawable-night/ic_play_arrow.xml
Labels: GUI, bug
