Repository TeamNewPipe/NewPipe, pull requests merged in 2022-07, with the labels that each got.

#8565 Run CI on all release branches
  .github/workflows/ci.yml
Labels: CI

#8564 Actually fix history view count
  app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntity.java
  app/src/main/java/org/schabi/newpipe/local/history/HistoryRecordManager.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, ASAP, player

#8549 [Localization] Fix lang code for Chinese Simplified (again!)
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: bug, localisation / translation

#8468 Clean up proguard file
  app/proguard-rules.pro
Labels: codequality

#8397 Add download to longpress menu
  app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogDefaultEntry.java
  app/src/main/java/org/schabi/newpipe/util/SparseItemUtil.java
Labels: enhancement, GUI

#8536 Update ExoPlayer to 2.18.0
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/datasource/YoutubeHttpDataSource.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java
  app/src/main/java/org/schabi/newpipe/player/playback/SurfaceHolderCallback.java
  app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
Labels: player

#8533 Crop the notification thumbnail in 1:1 mode instead of stretching it
  app/src/main/java/org/schabi/newpipe/player/NotificationUtil.java
  app/src/main/res/values/strings.xml
Labels: GUI, notification

#8469 Specify used ExoPlayer libraries
  app/build.gradle
Labels: codequality

#8573 Make thumbnails' `scaleType` `fitCenter`
  app/src/main/res/layout/channel_header.xml
  app/src/main/res/layout/item_stream_segment.xml
  app/src/main/res/layout/list_playlist_grid_item.xml
  app/src/main/res/layout/list_playlist_item.xml
  app/src/main/res/layout/list_playlist_mini_item.xml
  app/src/main/res/layout/list_stream_grid_item.xml
  app/src/main/res/layout/list_stream_item.xml
  app/src/main/res/layout/list_stream_mini_item.xml
  app/src/main/res/layout/list_stream_playlist_grid_item.xml
  app/src/main/res/layout/list_stream_playlist_item.xml
  app/src/main/res/layout/play_queue_item.xml
Labels: enhancement, GUI, multiservice

#8569 Use minimum required permissions for GitHub workflows
  .github/workflows/ci.yml
  .github/workflows/image-minimizer.yml
  .github/workflows/no-response.yml
Labels: CI

#8542 Add 'Share playlist' option to Playlist fragment
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/res/menu/menu_local_playlist.xml
Labels: enhancement

#8642 Rename "waiting-for-author" label to "waiting for author"
  .github/workflows/no-response.yml
Labels: meta

#8601 Checkstyle assign on same line
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoItemBuilder.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogDefaultEntry.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java
  app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationConstants.java
  app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/org/schabi/newpipe/settings/UpdateSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/streams/DataReader.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/PeertubeHelper.java
  app/src/main/java/org/schabi/newpipe/util/PermissionHelper.java
  app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
  app/src/main/java/org/schabi/newpipe/util/StateSaver.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/InternalUrlsHandler.java
  app/src/main/java/org/schabi/newpipe/util/urlfinder/PatternsCompat.java
  app/src/main/java/org/schabi/newpipe/views/FocusAwareDrawerLayout.java
  app/src/test/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelperTest.java
  app/src/test/java/org/schabi/newpipe/settings/tabs/TabsJsonHelperTest.java
  checkstyle/checkstyle.xml
Labels: codequality

#8475 Update some misc libraries
  app/build.gradle
  build.gradle
Labels: codequality

#8635 Use stream sorting.
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistLocalItem.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
Labels: codequality

#8631 Use Java 9 collection factories.
  app/src/main/java/com/google/android/material/appbar/FlingBehavior.java
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailPlayerCrasher.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogDefaultEntry.java
  app/src/main/java/org/schabi/newpipe/player/gesture/CustomBottomSheetBehavior.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchConfiguration.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchItem.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/TabsJsonHelper.java
  app/src/main/java/org/schabi/newpipe/util/CookieUtils.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/PeertubeHelper.java
  app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
  app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
Labels: codequality

#8679 Fix ListHelperTest failure caused by immutable list being used
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
Labels: bug

#8676 Fix wrong thumbnail used as placeholder for channel
  app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/subscription/item/ChannelItem.kt
Labels: bug, GUI

#8648 Use IO extensions.
  app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
  app/src/main/java/org/schabi/newpipe/util/ReleaseVersionUtil.kt
Labels: codequality

#8663 Remove unnecessary methods.
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
Labels: codequality

#8670 Remove deprecated method calls in FocusAwareCoordinator.
  app/src/main/java/org/schabi/newpipe/views/FocusAwareCoordinator.java
Labels: codequality

#8621 Deduplicate SQL queries to get feed streams
  app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedDatabaseManager.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
Labels: codequality

#8637 Removed the "(beta)"-tag from services
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
Labels: GUI

#8643 Add "needs triage" label to issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: meta
