Repository TeamNewPipe/NewPipe, pull requests merged in 2022-08, with the labels that each got.

#8661 Fix random NullPointerException when adding video player view
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, player

#8701 Use Throwable.stackTraceToString().
  app/src/main/java/org/schabi/newpipe/error/ErrorInfo.kt
Labels: codequality

#8656 Use WindowMetrics API.
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: codequality

#8669 Remove uses of setBottomSheetCallback().
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: codequality

#8682 Refactor LicenseFragmentHelper.
  app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
Labels: codequality

#8721 Make OnClickGesture an interface.
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/util/OnClickGesture.java
Labels: codequality

#8737 Replace coerceIn() with MathUtils.clamp().
  app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt
Labels: bug

#8724 Use toArray() with zero-length arrays.
  app/src/main/java/androidx/fragment/app/FragmentStatePagerAdapterMenuWorkaround.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationConstants.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
  app/src/main/java/org/schabi/newpipe/streams/WebMReader.java
Labels: codequality

#8728 Use Comparator factory methods.
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceFuzzySearchFunction.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
Labels: codequality

#8738 Use Collectors.joining().
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceParser.java
  app/src/main/java/org/schabi/newpipe/util/CookieUtils.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: codequality

#8719 Use ListAdapter for search predictions.
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchAdapter.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchFragment.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearcher.java
Labels: enhancement, GUI

#8822 Add FAQ entry to the template checklists
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: meta

#8755 Remove extra whitespace from issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#8677 Keep strong references to Picasso notification icon loading targets
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
  app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
Labels: bug, notification

#8678 Create media session UI and fix player notification
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionCallback.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueueNavigator.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java
  app/src/main/java/org/schabi/newpipe/player/ui/PlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.java
  app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
Labels: bug, player, notification

#8731 Fix surface view not resizing video correctly + other player fixes
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, player
