Repository TeamNewPipe/NewPipe, pull requests merged in 2022-04, with the labels that each got.

#8115 Update NewpipeExtractor
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/us/shandian/giga/get/DownloadMissionRecover.java
  app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.kt
  app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
Labels: bug, enhancement

#8020 ExoPlayer 2.17.1 update and MediaSource management rework
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailPlayerCrasher.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceEventListener.java
  app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
  app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java
  app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/ExceptionTag.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/PlaceholderTag.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/StreamInfoTag.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueueNavigator.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/PlayQueuePlaybackController.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/FailedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/ManagedMediaSourcePlaylist.java
  app/src/main/java/org/schabi/newpipe/player/mediasource/PlaceholderMediaSource.java
  app/src/main/java/org/schabi/newpipe/player/playback/CustomTrackSelector.java
  app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
  app/src/main/java/org/schabi/newpipe/player/playback/PlaybackListener.java
  app/src/main/java/org/schabi/newpipe/player/playback/SurfaceHolderCallback.java
  app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/MediaSourceTag.java
  app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
Labels: enhancement, player

#7516 Fix download dialog selector layout
  app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
Labels: bug, GUI

#8139 Fix fetch of video streams (when switching between tracks in a play queue) and subtitles when using a seamless transition between background and video players
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#8127 Fix `SparseItemUtil` so we don't enqueue twice
  app/src/main/java/org/schabi/newpipe/util/SparseItemUtil.java
Labels: bug, player

#8146 Use newInstance in PlaylistDialog
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistCreationDialog.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistDialog.java
Labels: bug

#8150 Fix caption auto-selection not reflected in player GUI
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
Labels: bug, player

#8249 Fix disabled caption to no longer automatically re-enable on new player instance
  .github/workflows/ci.yml
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#8236 Fix proguard for notification preference fragment
  app/proguard-rules.pro
Labels: bug

#8233 Fix new streams notifications preference screen
  app/src/main/java/org/schabi/newpipe/settings/NotificationsSettingsFragment.kt
Labels: bug, GUI

#8244 Fix crash when open NewPipe from notification bar
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
Labels: bug

#8279 Adapt opacity of popup close button to allow touches in other apps on Android >=12
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
Labels: bug, player, device/software specific

#8269 Update User-Agent in Downloader
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
Labels: enhancement

#7989 Rewrote ``PlaybackParameterDialog``
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerSemitoneHelper.java
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
  app/src/main/res/layout/dialog_playback_parameter.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, codequality
