Repository TeamNewPipe/NewPipe, pull requests merged in 2022-02, with the labels that each got.

#7661 Increase playlist stuck target duration coefficient and catch BehindLiveWindowExceptions properly
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
Labels: bug, player

#7776 Merge ``master`` branch back into ``dev``
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/982.txt
Labels: meta

#7682 Update FUNDING.yml
  .github/FUNDING.yml
Labels: meta

#7710 Small changes to license section of README
  README.md
Labels: meta

#7704 Fix crash when long-pressing stream while player is starting
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
Labels: bug, player

#7803 Add some stuff to `paths-ignore`
  .github/workflows/ci.yml
Labels: meta, CI

#7852 Set workaround for playback position reset when switching to main player with content thumbnail
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, player

#7772 Added image-minimizer
  .github/workflows/image-minimizer.js
  .github/workflows/image-minimizer.yml
Labels: meta

#7860 Use the correct app language when searching in the settings
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
Labels: bug, GUI

#7773 Switch to GitHub issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/ci.yml
Labels: meta

#7884 Improved image-minimizer
  .github/workflows/image-minimizer.js
Labels: bug, meta

#7893 Fix fast seek overlay arc not correctly centered
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, GUI, player

#7659 Load enough initial items (into BaseListFragment and descendants)
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
  checkstyle-suppressions.xml
Labels: bug, GUI

#7898 Have fast seek overlay arc go under system ui
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, GUI, player

#7901 Small refactor in player class
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: codequality

#7924 Revert "Respect cutouts when playing in MultiWindow"
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug

#7904 Solve Java warning "Raw use of parameterized class"
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/kiosk/KioskFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelper.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/ChannelPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlaylistPlayQueue.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/SerializedCache.java
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
Labels: codequality

#7905 Fix Room warning about unused columns during build
  app/src/main/java/org/schabi/newpipe/database/history/dao/StreamHistoryDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
  app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
Labels: codequality

#7349 Add seamless transition between background and video players when putting the app in background (for video-only streams and audio-only streams only)
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
  checkstyle-suppressions.xml
Labels: enhancement, player

#7782 Fix build on Apple Silicon macs
  app/build.gradle
Labels: bug, device/software specific

#7894 Remove large-land player layout: not actually used
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/player.xml
Labels: GUI, player, codequality
