Repository TeamNewPipe/NewPipe, pull requests merged in 2022-05, with the labels that each got.

#8329 Removed unused ``strings.xml`` resources
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-ckb/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: codequality

#8349 Fixed accidental reset of ``PlaybackParameterDialog`` on initialization
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
Labels: bug, player

#8315 Fix hiding player controls when playing from media button
  app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
Labels: bug, player

#8332 Fix Routeractivity theming
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/res/values/styles.xml
Labels: bug

#8192 Fix crash when rotating device on unsupported channels
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Labels: bug, GUI

#8355 HI translation to `README.md`
  README.md
  doc/README.es.md
  doc/README.hi.md
  doc/README.ja.md
  doc/README.ko.md
  doc/README.pl.md
  doc/README.pt_BR.md
  doc/README.ro.md
  doc/README.so.md
  doc/README.tr.md
  doc/README.zh_TW.md
Labels: localisation / translation

#8377 Make volume progress bar match system volume when we start sliding
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
Labels: bug, player

#7355 Add a "Add to playlist" item to the remote playlist menu
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/res/menu/menu_playlist.xml
Labels: enhancement

#7458 Moved subscription import/export options to (overflow) menu
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedImportExportItem.kt
  app/src/main/java/org/schabi/newpipe/settings/PeertubeInstanceListFragment.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/res/drawable-nodpi/place_holder_bandcamp.png
  app/src/main/res/drawable-nodpi/place_holder_circle.png
  app/src/main/res/drawable-nodpi/place_holder_cloud.png
  app/src/main/res/drawable-nodpi/place_holder_gadse.png
  app/src/main/res/drawable-nodpi/place_holder_peertube.png
  app/src/main/res/drawable-nodpi/place_holder_youtube.png
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_cloud.xml
  app/src/main/res/drawable/ic_placeholder_bandcamp.xml
  app/src/main/res/drawable/ic_placeholder_media_ccc.xml
  app/src/main/res/drawable/ic_placeholder_peertube.xml
  app/src/main/res/drawable/ic_smart_display.xml
  app/src/main/res/layout/drawer_header.xml
  app/src/main/res/layout/feed_import_export_group.xml
  app/src/main/res/layout/item_instance.xml
  app/src/main/res/layout/subscription_import_export_item.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/styles_misc.xml
Labels: enhancement, GUI

#8413 Spanish Readme fix [Corrige frase de README]
  doc/README.es.md
Labels: localisation / translation

#8143 Add image preview of the content shared where possible in Android share sheet (for Android 10+ devices only)
  app/src/main/java/org/schabi/newpipe/util/PicassoHelper.java
  app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
Labels: enhancement, GUI, device/software specific

#8391 Use JvmOverloads.
  app/src/main/java/org/schabi/newpipe/ktx/View.kt
Labels: codequality

#8382 Remove unnecessary compat method calls.
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
Labels: codequality

#8404 Use AppCompatResources.
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
Labels: codequality
