Repository TeamNewPipe/NewPipe, pull requests merged in 2022-12, with the labels that each got.

#8883 Only show "Enqueue next" when in the middle of the queue
  app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
Labels: player

#9173 Show subscriber count on video details page
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: feature request, GUI

#9504 [PeerTube] Remove dead Privacy Tools instance
  app/src/main/AndroidManifest.xml
Labels: peertube

#9522 Update translations
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-is/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-or/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-und/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/es/changelogs/991.txt
Labels: localisation / translation

#9596 Update translations
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-ur/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values/settings_keys.xml
  fastlane/metadata/android/fr/changelogs/740.txt
  fastlane/metadata/android/fr/changelogs/991.txt
  fastlane/metadata/android/it/changelogs/740.txt
  fastlane/metadata/android/te/changelogs/65.txt
  fastlane/metadata/android/uk/changelogs/951.txt
Labels: localisation / translation

#9488 Disabling night theme selection if auto theme is not used
  app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
  app/src/main/res/values/strings.xml
Labels: GUI

#8895 Use SparseArrayCompat.
  app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHolder.java
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
  app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
Labels: codequality

#9159 Refactor VideoPlayerUi.
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
Labels: codequality

#9496 Seeking no longer pauses the played video
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
Labels: feature request, GUI, player

#9502 Added option to download items in the queue
  app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java
  app/src/main/res/menu/menu_play_queue_item.xml
Labels: feature request, downloader, queue
