Repository TeamNewPipe/NewPipe, pull requests merged in 2022-01, with the labels that each got.

#7607 Fixed search not accepting key input after closing player overlay
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, player

#7636 CI: Upload test-report when an error occurs
  .github/workflows/ci.yml
Labels: CI

#7654 Replace JUnit asserts with AssertJ in HistoryRecordManagerTest
  app/build.gradle
  app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt
  app/src/main/java/org/schabi/newpipe/database/history/model/SearchHistoryEntry.java
  app/src/main/java/org/schabi/newpipe/database/history/model/SearchHistoryEntry.kt
Labels: codequality

#7662 Fix crash when sharing a playlist which is loading
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
Labels: bug, GUI

#7668 Workaround: Set recovery before switching player
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, ASAP, player

#7648 Fix false warning
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Labels: codequality

#7674 Make SearchHistoryEntry.kt fields nullable to match java version
  app/src/main/java/org/schabi/newpipe/database/history/model/SearchHistoryEntry.kt
Labels: bug

#7618 Add traditional Chinese README
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  README.tr.md
  README.zh_TW.md
Labels: meta, localisation / translation

#7317 Some untranslatable string improvements
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
Labels: codequality

#7670 Ensure order of search history entries in tests
  .github/workflows/ci.yml
  app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt
  app/src/androidTest/java/org/schabi/newpipe/local/playlist/LocalPlaylistManagerTest.kt
Labels: bug

#7672 Add app icon to fastlane metadata
  fastlane/metadata/android/en-US/images/icon.png
Labels: meta

#7566 Android TV banner with text
  app/src/main/res/mipmap-xhdpi/newpipe_tv_banner.png
  assets/android-tv-banner.svg
Labels: device/software specific, Android TV

#7614 Revert #7568
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/values/strings.xml
Labels: bug, GUI

#7699 Sync weblate v2
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sv/strings.xml
Labels: ASAP, localisation / translation

#7693 Fix first item always played in the play queue when reloading play queue manager
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, ASAP, player

#7538 Load uploaderUrl when showing Channel Details from Play Queue
  app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java
  app/src/main/java/org/schabi/newpipe/util/SaveUploaderUrlHelper.java
  app/src/main/java/org/schabi/newpipe/util/StreamDialogEntry.java
Labels: bug

#7700 Improve HistoryRecordManager tests
  app/src/androidTest/java/org/schabi/newpipe/local/history/HistoryRecordManagerTest.kt
Labels: codequality

#4833 YouTube's Fast Forward/Rewind behavior
  app/src/main/java/org/schabi/newpipe/ktx/View.kt
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/BasePlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/event/PlayerGestureListener.java
  app/src/main/java/org/schabi/newpipe/views/player/CircleClipTapView.kt
  app/src/main/java/org/schabi/newpipe/views/player/PlayerFastSeekOverlay.kt
  app/src/main/java/org/schabi/newpipe/views/player/SecondsView.kt
  app/src/main/res/drawable/ic_play_seek_triangle.xml
  app/src/main/res/layout-large-land/player.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/layout/player_fast_seek_overlay.xml
  app/src/main/res/layout/player_fast_seek_seconds_view.xml
Labels: enhancement, GUI, player

#7586 Made preferences searchable
  .gitignore
  app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsBVDLeakCanary.java
  app/src/debug/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
  app/src/main/java/org/apache/commons/text/similarity/FuzzyScore.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/settings/AppearanceSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/BasePreferenceFragment.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DebugSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/HistorySettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/MainSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/NotificationSettingsFragment.kt
  app/src/main/java/org/schabi/newpipe/settings/SelectKioskFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsResourceRegistry.java
  app/src/main/java/org/schabi/newpipe/settings/UpdateSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceFuzzySearchFunction.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceParser.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchAdapter.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchConfiguration.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchFragment.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchItem.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchResultHighlighter.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchResultListener.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearcher.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/package-info.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/ChooseTabsFragment.java
  app/src/main/java/org/schabi/newpipe/util/KeyboardUtil.java
  app/src/main/res/layout/settings_layout.xml
  app/src/main/res/layout/settings_preferencesearch_fragment.xml
  app/src/main/res/layout/settings_preferencesearch_list_item_result.xml
  app/src/main/res/menu/menu_settings_main_fragment.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
  app/src/main/res/xml/history_settings.xml
  app/src/main/res/xml/main_settings.xml
  app/src/main/res/xml/update_settings.xml
  app/src/release/res/xml/main_settings.xml
Labels: enhancement, GUI

#7694 Polish translation of README
  README.es.md
  README.ja.md
  README.ko.md
  README.md
  README.pl.md
  README.pt_BR.md
  README.ro.md
  README.so.md
  README.tr.md
  README.zh_TW.md
Labels: meta, localisation / translation
