Repository TeamNewPipe/NewPipe, pull requests merged in 2022-03, with the labels that each got.

#7728 Remember adjustment step size for playback controls (speed and pitch)
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/res/values/settings_keys.xml
Labels: enhancement, player

#7341 Fix player controls not hiding if resumed from media button
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/playback/PlayerMediaSession.java
Labels: bug, player

#7963 Improve player UI and navigability for Android TV
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/res/layout/player.xml
  app/src/main/res/values/styles_misc.xml
Labels: GUI, Android TV

#7978 Update some AndroidX libraries
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/settings/custom/DurationListPreference.kt
Labels: codequality

#5878 Add a confirmation button when deleting all files in downloader
  app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java
  app/src/main/res/values/strings.xml
Labels: enhancement, downloader

#7981 Deduplicate code for fetching stream info when sparse
  app/src/main/java/org/schabi/newpipe/QueueItemMenuUtil.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogDefaultEntry.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/StreamDialogEntry.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/SaveUploaderUrlHelper.java
  app/src/main/java/org/schabi/newpipe/util/SparseItemUtil.java
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+zh+HANS+CN/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-ckb/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-ml/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-so/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: codequality

#8065 Clean up the about package a bit
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
Labels: codequality

#8066 Create stub implementation for OnSeekBarChangeListener
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/util/SimpleOnSeekBarChangeListener.kt
  app/src/main/java/org/schabi/newpipe/views/player/SecondsView.kt
Labels: player, codequality

#8068 Some lint cleaning
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/OnScrollBelowItemsListener.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/StackItem.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SuggestionListAdapter.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistDialog.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/history/HistoryEntryAdapter.java
  app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupReorderDialog.kt
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/helper/AudioReactor.java
  app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java
  app/src/main/java/org/schabi/newpipe/player/helper/MediaSessionManager.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlaybackParameterDialog.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsActivity.java
  app/src/main/java/org/schabi/newpipe/settings/SettingsResourceRegistry.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchConfiguration.java
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceSearchItem.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java
  app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
Labels: codequality

#8073 Update checkstyle to 10.0 and fix various related issues
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueueItem.java
  app/src/main/java/org/schabi/newpipe/streams/Mp4FromDashWriter.java
  app/src/main/java/org/schabi/newpipe/streams/WebMWriter.java
  checkstyle-suppressions.xml
  checkstyle/checkstyle.xml
  checkstyle/suppressions.xml
Labels: codequality

#8076 Update license to latest version
  LICENSE
Labels: meta

#8077 Delete copyright-file
  copyright
Labels: meta

#7977 Fix error notification on KitKat
  app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
Labels: bug, device/software specific
