Repository TeamNewPipe/NewPipe, pull requests merged in 2022-11, with the labels that each got.

#9272 Update PrettyTime from 5.0.3 to 5.0.6 to include new localizations
  app/build.gradle
Labels: localisation / translation

#9230 Fix duplicate videos in feed group "All"
  app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
Labels: bug, feed

#9291 Support YouTube handles and update NewPipe Extractor
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: bug, feature request, youtube, multiservice

#9109 Hide play queue button in VideoDetailsFragment when queue is empty
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
Labels: bug, GUI, player

#9298 Fix inconsistent channel group list and items view mode
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/item/FeedGroupCarouselItem.kt
Labels: bug, GUI

#9333 Make PendingIntents immutable on Android 6.0 and later.
  app/src/main/java/org/schabi/newpipe/NewVersionWorker.kt
  app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/util/PendingIntentCompat.java
  app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
Labels: bug, device/software specific

#8316 Fix persistent hover overlay when in desktop/DeX mode or using a mouse/non-touch input
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: bug, GUI, player, device/software specific

#8870 Use Locale.forLanguageTag().
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: codequality

#8961 Remove the redundant/overlapping toast "Copied to clipboard" for Android 13+
  app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/java/us/shandian/giga/util/Utility.java
Labels: feature request, device/software specific

#9471 Set image-minimizer to specify image width ...
  .github/workflows/image-minimizer.js
Labels: meta

#8743 Remove padding from the end of the mini-player
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: feature request, GUI
