Repository TeamNewPipe/NewPipe, pull requests merged in 2022-06, with the labels that each got.

#8340 Fix "Add to playlist" not working and cleanup "RouterActivity" choice handling
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailPlayerCrasher.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
  app/src/main/res/layout/single_choice_dialog_view.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/styles.xml
Labels: bug

#8153 Support delivery methods other than progressive HTTP
  app/build.gradle
  app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/database/stream/dao/StreamDAO.kt
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/datasource/NonUriHlsDataSourceFactory.java
  app/src/main/java/org/schabi/newpipe/player/datasource/YoutubeHttpDataSource.java
  app/src/main/java/org/schabi/newpipe/player/helper/CacheFactory.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerDataSource.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/player/listeners/view/QualityClickListener.kt
  app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/SecondaryStreamHelper.java
  app/src/main/java/org/schabi/newpipe/util/SparseItemUtil.java
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
  app/src/main/java/org/schabi/newpipe/util/StreamTypeUtil.java
  app/src/main/java/us/shandian/giga/get/DownloadMissionRecover.java
  app/src/main/java/us/shandian/giga/get/MissionRecoveryInfo.kt
  app/src/main/res/layout/download_dialog.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
Labels: bug, enhancement, youtube, multiservice, player, peertube

#8372 Made some much needed changes to the ReadMe
  README.md
Labels: meta
