Repository TeamNewPipe/NewPipe, pull requests merged in 2022-10, with the labels that each got.

#8987 Add monochrome icon
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: enhancement, GUI

#8934 Use LinkifyCompat.
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
Labels: codequality

#9011 Utilize useSimpleSummaryProvider attribute
  app/src/main/res/xml/appearance_settings.xml
  app/src/main/res/xml/content_settings.xml
  app/src/main/res/xml/download_settings.xml
  app/src/main/res/xml/notifications_settings.xml
  app/src/main/res/xml/video_audio_settings.xml
Labels: codequality

#8734 Improve `FeedGroupDialogViewModel` factory
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
Labels: codequality

#9065 Fix potential cast exception in comments text
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
Labels: bug

#9079 Fix `DownloadDialog` crash on screen rotation
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Labels: bug

#9164 Add Link to FAQ in the app
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
Labels: feature request, GUI

#9180 Add an Open in browser button on error panel
  app/src/main/java/org/schabi/newpipe/error/ErrorPanelHelper.kt
  app/src/main/res/layout/error_panel.xml
Labels: feature request, GUI

#9179 Added Icelandic, Latvian, Malayalam to language selector
  app/src/main/res/values-ayc/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-is/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-pa-rPK/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-und/strings.xml
  app/src/main/res/values/settings_keys.xml
  fastlane/metadata/android/es/changelogs/66.txt
  fastlane/metadata/android/eu/changelogs/66.txt
  fastlane/metadata/android/eu/changelogs/68.txt
  fastlane/metadata/android/eu/changelogs/69.txt
  fastlane/metadata/android/eu/changelogs/70.txt
  fastlane/metadata/android/eu/changelogs/71.txt
  fastlane/metadata/android/eu/changelogs/730.txt
  fastlane/metadata/android/eu/changelogs/740.txt
  fastlane/metadata/android/eu/changelogs/750.txt
  fastlane/metadata/android/eu/changelogs/760.txt
  fastlane/metadata/android/eu/changelogs/770.txt
  fastlane/metadata/android/eu/changelogs/780.txt
  fastlane/metadata/android/eu/changelogs/790.txt
  fastlane/metadata/android/eu/changelogs/988.txt
  fastlane/metadata/android/eu/changelogs/989.txt
  fastlane/metadata/android/eu/changelogs/990.txt
  fastlane/metadata/android/fr/changelogs/810.txt
  fastlane/metadata/android/is/full_description.txt
  fastlane/metadata/android/is/short_description.txt
  fastlane/metadata/android/it/changelogs/988.txt
  fastlane/metadata/android/it/changelogs/989.txt
  fastlane/metadata/android/it/changelogs/990.txt
  fastlane/metadata/android/pa-PK/short_description.txt
  fastlane/metadata/android/pl/changelogs/65.txt
  fastlane/metadata/android/ru/changelogs/71.txt
  fastlane/metadata/android/sv/changelogs/66.txt
  fastlane/metadata/android/sv/changelogs/68.txt
  fastlane/metadata/android/sv/changelogs/69.txt
  fastlane/metadata/android/sv/changelogs/70.txt
  fastlane/metadata/android/sv/changelogs/71.txt
  fastlane/metadata/android/sv/changelogs/740.txt
  fastlane/metadata/android/sv/changelogs/750.txt
  fastlane/metadata/android/sv/changelogs/760.txt
  fastlane/metadata/android/sv/changelogs/780.txt
Labels: localisation / translation

#8747 Use range-limiting methods in more places.
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/player/gesture/MainPlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java
  app/src/main/java/org/schabi/newpipe/util/ReleaseVersionUtil.kt
Labels: codequality

#8767 Use Okio's ByteString for download checksums.
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/java/us/shandian/giga/util/Utility.java
Labels: codequality

#8706 Refactor removeWatchedStreams() in LocalPlaylistFragment.
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Labels: codequality, playlist

#8739 Calculate search score using streams.
  app/src/main/java/org/schabi/newpipe/settings/preferencesearch/PreferenceFuzzySearchFunction.java
Labels: codequality

#9203 Added timestamped link sharing from the start of a chapter with a long hold press
  app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentAdapter.kt
  app/src/main/java/org/schabi/newpipe/info_list/StreamSegmentItem.kt
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
Labels: feature request, player

#9256 Update translations and remove empty localizations
  app/src/main/res/values-ang/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ars/strings.xml
  app/src/main/res/values-ay/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dum/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-enm/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-ks/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-nds/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-scn/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/settings_keys.xml
  fastlane/metadata/android/he/changelogs/985.txt
  fastlane/metadata/android/pt/changelogs/990.txt
Labels: localisation / translation
