Repository TeamNewPipe/NewPipe, pull requests merged in 2023-08, with the labels that each got.

#10275 Fix player audio focus not respecting mute
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player

#10331 Make "latest release" link more obvious to bug reporters
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: meta

#10360 Simplify `MainActivity.tabSelected(MenuItem)`
  app/src/main/java/org/schabi/newpipe/MainActivity.java
Labels: codequality

#10376 Fix string formats
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-be/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-my/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-or/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-ryu/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sq/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-ur/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  fastlane/metadata/android/cs/changelogs/994.txt
  fastlane/metadata/android/ml/changelogs/64.txt
  fastlane/metadata/android/pt-PT/changelogs/994.txt
  fastlane/metadata/android/pt/changelogs/994.txt
  fastlane/metadata/android/uk/changelogs/994.txt
Labels: bug, localisation / translation

#10377 Image minizier: replace Number.toFixed(0) with Math.floor()
  .github/workflows/image-minimizer.js
Labels: meta, codequality

#10396 Show play queue button in main player when there is one stream
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
Labels: feature request, player
