Repository TeamNewPipe/NewPipe, pull requests merged in 2023-07, with the labels that each got.

#10213 Update screenshots
  README.md
  doc/README.es.md
  doc/README.hi.md
  doc/README.ja.md
  doc/README.ko.md
  doc/README.pl.md
  doc/README.pt_BR.md
  doc/README.ro.md
  doc/README.so.md
  doc/README.tr.md
  doc/README.zh_TW.md
  fastlane/metadata/android/en-US/images/phoneScreenshots/00.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/01.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/02.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/03.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/04.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/05.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/06.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/07.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/08.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_01.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_02.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_03.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_04.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_05.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_06.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_07.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_08.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_09.png
  fastlane/metadata/android/en-US/images/phoneScreenshots/shot_10.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/09.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/10.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/shot_11.png
  fastlane/metadata/android/en-US/images/tenInchScreenshots/shot_12.png
Labels: meta

#10166 Add support for new GitHub assets URLs in image minimizer workflow
  .github/workflows/image-minimizer.js
Labels: meta

#10219 Add link to wiki page for APK download
  .github/PULL_REQUEST_TEMPLATE.md
Labels: meta

#10085 Update LeakCanary library
  app/build.gradle
  app/src/debug/java/org/schabi/newpipe/DebugApp.kt
  app/src/main/java/org/schabi/newpipe/BaseFragment.java
Labels: codequality

#10229 Fix crash after feed update
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
Labels: bug, feed

#9897 Update README.es.md
  doc/README.es.md
Labels: localisation / translation

#9421 Update README.ko.md
  doc/README.ko.md
Labels: meta, localisation / translation

#10232 Fix LeakCanary startup in debug builds and fix a memory leak
  app/build.gradle
  app/src/debug/java/org/schabi/newpipe/DebugApp.kt
  app/src/main/java/org/schabi/newpipe/BaseFragment.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
Labels: bug, player, codequality, dependency

#10230 [Download] Fix audio stream selection
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
Labels: bug, downloader

#8456 Add database test for SubscriptionManager
  app/src/androidTest/java/org/schabi/newpipe/local/subscription/SubscriptionManagerTest.java
Labels: codequality, database

#9719 Added bottom main-tabs feature
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/appearance_settings.xml
Labels: feature request, GUI

#10235 Update AndroidX Room library
  app/build.gradle
  app/src/androidTest/java/org/schabi/newpipe/database/DatabaseMigrationTest.kt
  app/src/main/java/org/schabi/newpipe/database/feed/model/FeedGroupSubscriptionEntity.kt
Labels: codequality, dependency

#10078 Improve new stream notifications
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationWorker.kt
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/drawable-hdpi/ic_newpipe_triangle_white.png
  app/src/main/res/drawable-mdpi/ic_newpipe_triangle_white.png
  app/src/main/res/drawable-xhdpi/ic_newpipe_triangle_white.png
  app/src/main/res/drawable-xxhdpi/ic_newpipe_triangle_white.png
  app/src/main/res/drawable-xxxhdpi/ic_newpipe_triangle_white.png
Labels: feature request, GUI, new stream notification

#10233 Minimize images in PR descriptions
  .github/workflows/image-minimizer.js
  .github/workflows/image-minimizer.yml
Labels: meta

#10250 Added Uchinaguchi translation and README
  app/src/main/res/values-ryu/strings.xml
  app/src/main/res/values/settings_keys.xml
  doc/README.asm.md
  doc/README.de.md
  doc/README.es.md
  doc/README.fr.md
  doc/README.hi.md
  doc/README.it.md
  doc/README.ja.md
  doc/README.ko.md
  doc/README.pa.md
  doc/README.pl.md
  doc/README.pt_BR.md
  doc/README.ro.md
  doc/README.ru.md
  doc/README.ryu.md
  doc/README.so.md
  doc/README.tr.md
  doc/README.zh_TW.md
Labels: meta, localisation / translation

#10281 Update com.squareup.okio:okio to 3.4.0
  app/build.gradle
Labels: dependency

#10122 Disable media tunneling by default on known unsupported devices
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsManager.kt
  app/src/main/java/org/schabi/newpipe/settings/ExoPlayerSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
Labels: bug, player, Android TV
