Repository TeamNewPipe/NewPipe, pull requests merged in 2023-09, with the labels that each got.

#10406 Fix language Picker Selecting Wrong Languages
  app/src/main/res/values/settings_keys.xml
Labels: bug, localisation / translation

#10234 Update miscellaneous libraries
  app/build.gradle
  build.gradle
Labels: dependency

#10248 Improve the download helpers using the Java 7 NIO API.
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/streams/io/StoredDirectoryHelper.java
  app/src/main/java/org/schabi/newpipe/streams/io/StoredFileHelper.java
Labels: downloader, codequality

#10407 Improved downloading experience
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/download/LoadingDialog.java
  app/src/main/res/layout/download_loading_dialog.xml
  app/src/main/res/values/strings.xml
Labels: feature request, downloader, GUI

#9182 Add support for channel tabs
  app/build.gradle
  app/src/androidTest/java/org/schabi/newpipe/local/subscription/SubscriptionManagerTest.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/BaseDescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelAboutFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelTabFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistControlViewHolder.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedState.kt
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedUpdateInfo.kt
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/ChannelPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/ChannelTabPlayQueue.java
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/util/ChannelTabHelper.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/PlayButtonHelper.java
  app/src/main/res/drawable-nodpi/placeholder_channel_banner.png
  app/src/main/res/layout/channel_header.xml
  app/src/main/res/layout/fragment_channel.xml
  app/src/main/res/layout/fragment_channel_tab.xml
  app/src/main/res/layout/fragment_channel_videos.xml
  app/src/main/res/layout/fragment_description.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/content_settings.xml
Labels: feature request, GUI, multiservice, deep review required

#10165 Fix downloads of streams with missing MediaFormat
  app/src/androidTest/java/org/schabi/newpipe/util/StreamItemAdapterTest.kt
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/util/AudioTrackAdapter.java
  app/src/main/java/org/schabi/newpipe/util/SecondaryStreamHelper.java
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
Labels: bug, soundcloud, downloader

#10224 Replace MathUtils.clamp with Kotlin coerceIn
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/player/gesture/MainPlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt
Labels: codequality

#10244 Update Google Material library
  app/build.gradle
Labels: dependency

#10428 Bump AGP to 8.1.1
  app/src/main/java/org/schabi/newpipe/streams/io/StoredDirectoryHelper.java
  build.gradle
Labels: dependency

#10435 Improve codequality
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/SinglePlayQueue.java
  app/src/main/java/us/shandian/giga/get/DownloadInitializer.java
  app/src/main/java/us/shandian/giga/io/CircularFileWriter.java
  app/src/main/java/us/shandian/giga/service/DownloadManager.java
Labels: codequality

#10199 Improved accessibility of player interfaces
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
  app/src/main/res/layout-land/activity_player_queue_control.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/play_queue_item.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/layout/player_popup_close_overlay.xml
  app/src/main/res/values/strings.xml
Labels: player, accessibility

#10170 Add workflow "PR size labeler" to label PRs based on the number of changed lines
  .github/changed-lines-count-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: meta

#9987 Include a high-resolution option in the default resolution settings.
  app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
Labels: feature request, player

#10447 Add write permission to PR labeler workflow
  .github/workflows/pr-labeler.yml
Labels: meta, size/small

#10453 Add content: read permission to PR size labeler workflow
  .github/workflows/pr-labeler.yml
Labels: meta, size/small

#10455 Fix PR labeler permissions
  .github/workflows/pr-labeler.yml
Labels: meta, size/small
