Repository TeamNewPipe/NewPipe, pull requests merged in 2023-11, with the labels that each got.

#10579 Remove OPUS HLS streams from playable streams
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
Labels: bug, player

#10578 Restore player service start handling before player UI separation and fix some issues in this service
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationPlayerUi.java
Labels: bug, player, player notification

#10577 Fix crash when building the play queue audio track menu if the player is null
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
Labels: bug, GUI

#10576 Fix crash when setting the masking of the new feed items button if the context is null
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
Labels: bug, feed

#10489 Quote filename replacement characters to fix crashes when downloading streams with special characters
  app/src/main/java/org/schabi/newpipe/util/FilenameUtils.java
Labels: bug, downloader
