Repository TeamNewPipe/NewPipe, pull requests merged in 2023-12, with the labels that each got.

#10494 Fix notifying about old "new" streams
  app/src/androidTest/java/org/schabi/newpipe/database/FeedDAOTest.kt
  app/src/main/java/org/schabi/newpipe/database/feed/dao/FeedDAO.kt
Labels: bug, feed, database, new stream notification

#10446 Improve audio stream selection for video-only streams in the downloader
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/SecondaryStreamHelper.java
Labels: bug, downloader

#10645 Fix crashes due to wrong root fragment manager
  app/src/main/java/org/schabi/newpipe/BaseFragment.java
Labels: bug, GUI, channel, size/small

#10671 Fix application lagging with many main page tabs
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
Labels: bug, GUI, channel, size/small

#10670 Fix OutOfMemory when fetching feed
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedUpdateInfo.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
Labels: bug, feed, size/medium

#10673 Fix transaction too large in channel tab fragments
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelTabFragment.java
Labels: bug, channel, size/small

#10018 Add support for comment replies
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/error/UserAction.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListInfoFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentRepliesFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentRepliesInfo.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsInfo.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoItemBuilder.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/java/org/schabi/newpipe/util/RelatedItemInfo.java
  app/src/main/java/org/schabi/newpipe/util/ServiceHelper.java
  app/src/main/res/layout/comment_replies_header.xml
  app/src/main/res/layout/fragment_comments.xml
  app/src/main/res/layout/list_comment_item.xml
  app/src/main/res/layout/list_comments_mini_item.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature request, multiservice, playlist, size/giant

#10086 Update some AndroidX libraries and compileSdk to 34
  app/build.gradle
  app/src/main/java/androidx/fragment/app/FragmentStatePagerAdapterMenuWorkaround.java
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/error/ErrorActivity.java
  app/src/main/java/org/schabi/newpipe/ktx/Bundle.kt
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationWorker.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
  app/src/main/java/org/schabi/newpipe/player/gesture/MainPlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/gesture/PopupPlayerGestureListener.kt
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/util/StateSaver.java
  app/src/main/java/org/schabi/newpipe/views/player/CircleClipTapView.kt
  app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
Labels: codequality, dependency

#10530 Update miscellaneous libraries
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/database/Converters.kt
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedEventManager.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialog.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/dialog/FeedGroupDialogViewModel.kt
  app/src/test/java/org/schabi/newpipe/local/subscription/FeedGroupIconTest.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependency

#10700 Newpipe 0.26.1
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelTabFragment.java
  fastlane/metadata/android/en-US/changelogs/996.txt
Labels: size/small

#10091 Add playlist description to playlist fragment
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/text/TextEllipsizer.java
  app/src/main/res/layout/playlist_header.xml
  app/src/main/res/values/strings.xml
Labels: feature request, GUI, multiservice, playlist, size/large

#10712 [Android 13+] Restore support of custom notification actions
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/SessionConnectorActionProvider.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationActionData.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationConstants.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationActionsPreference.java
  app/src/main/java/org/schabi/newpipe/settings/custom/NotificationSlot.java
  app/src/main/res/layout/settings_notification.xml
  app/src/main/res/values/strings.xml
Labels: bug, device/software specific, player notification, codequality
