Repository TeamNewPipe/NewPipe, pull requests merged in 2023-06, with the labels that each got.

#10087 Update some libraries
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: codequality

#10141 handle links to the PeerTube instance “peertube.stream”
  app/src/main/AndroidManifest.xml
Labels: peertube

#10066 Fix uploader and subchannel avatars being swapped and disable loading thumbnail message failure on content details page
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/res/layout-large-land/fragment_video_detail.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: bug, GUI, peertube
