Repository TeamNewPipe/NewPipe, pull requests merged in 2023-10, with the labels that each got.

#10466 Use PR labeler fork
  .github/workflows/pr-labeler.yml
Labels: meta, size/small

#10465 Create Serbian README
  README.md
  doc/README.asm.md
  doc/README.de.md
  doc/README.es.md
  doc/README.fr.md
  doc/README.hi.md
  doc/README.it.md
  doc/README.ja.md
  doc/README.ko.md
  doc/README.pa.md
  doc/README.pl.md
  doc/README.pt_BR.md
  doc/README.ro.md
  doc/README.ru.md
  doc/README.ryu.md
  doc/README.so.md
  doc/README.sr.md
  doc/README.tr.md
  doc/README.zh_TW.md
Labels: meta, localisation / translation

#8248 Fix inconsistency between user interaction and database commit order when re-adding videos to the playlist
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Labels: bug, database, playlist

#10482 Fix crash with disabled thumbnails when trying to play a stream
  app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java
Labels: bug, size/small

#10491 [README] Remove Bitcoin and Bountysource donation options
  README.md
  doc/README.asm.md
  doc/README.de.md
  doc/README.es.md
  doc/README.fr.md
  doc/README.hi.md
  doc/README.it.md
  doc/README.ja.md
  doc/README.ko.md
  doc/README.pa.md
  doc/README.pl.md
  doc/README.pt_BR.md
  doc/README.ro.md
  doc/README.ru.md
  doc/README.ryu.md
  doc/README.so.md
  doc/README.sr.md
  doc/README.tr.md
  doc/README.zh_TW.md
Labels: meta, size/medium
