Repository TeamNewPipe/NewPipe, pull requests merged in 2023-05, with the labels that each got.

#9948 [YouTube] Improve download speed
  app/src/main/java/us/shandian/giga/get/DownloadInitializer.java
  app/src/main/java/us/shandian/giga/util/Utility.java
Labels: bug, youtube, downloader

#9937 Add support for multiple audio tracks
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerEventListener.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/StreamInfoTag.java
  app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/VideoPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
  app/src/main/java/org/schabi/newpipe/util/AudioTrackAdapter.java
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/StreamItemAdapter.java
  app/src/main/res/layout/download_dialog.xml
  app/src/main/res/layout/player.xml
  app/src/main/res/menu/menu_play_queue.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/video_audio_settings.xml
  app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java
Labels: feature request, multiservice, player

#10046 Fix ktlint formatter after upgrade to Java 17
  app/build.gradle
Labels: meta

#10042 add language ߒߞߏ (nqo)
  app/src/main/res/values/settings_keys.xml
Labels: localisation / translation, template ignored

#10089 Fix unresolved extractor
  app/build.gradle
Labels: codequality
