Repository TeamNewPipe/NewPipe, pull requests merged in 2023-01, with the labels that each got.

#9568 Added icon for "Play All"
  app/src/main/res/layout/playlist_control.xml
Labels: feature request, GUI

#8841 Use ListAdapter in NotificationModeConfigAdapter.
  app/src/main/java/org/schabi/newpipe/settings/notifications/NotificationModeConfigAdapter.kt
  app/src/main/java/org/schabi/newpipe/settings/notifications/NotificationModeConfigFragment.kt
Labels: codequality

#9562 Support audio only background for services only supporting video streams
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/resolver/AudioPlaybackResolver.java
  app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java
Labels: feature request, player

#9553 Update ExoPlayer to 2.18.2
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/player/mediasource/LoadedMediaSource.java
Labels: player, codequality

#9285 Clean up Optional-related code.
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/mediaitem/MediaItemTag.java
  app/src/main/java/org/schabi/newpipe/player/playback/MediaSourceManager.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHelper.java
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
Labels: codequality

#9135 Improve screen rotation handling in Open action menu
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
Labels: bug, GUI

#9499 Added Language suffix for subtitle downloads
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/res/values/donottranslate.xml
Labels: feature request, downloader

#9653 Ask for permission when enqueuing in a popup
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: bug, player, queue

#9619 Check availability of Samsung DeX only on Samsung devices
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
Labels: GUI, device/software specific

#8886 Remove Runnable variables for Handlers.
  app/src/main/java/org/schabi/newpipe/player/gesture/BasePlayerGestureListener.kt
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/java/us/shandian/giga/ui/common/Deleter.java
Labels: codequality

#9445 Fixed a bug that incorrectly removed videos from a playlist when using the "Remove Viewed" dialog
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
Labels: bug, playlist

#9642 Fixed a bug that prevented the display of multiple empty playlists
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
Labels: bug, playlist

#8894 Use WindowCompat.
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
Labels: codequality

#9555 Made the channel-images in the grid list bigger
  app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/ChannelMiniInfoItemHolder.java
  app/src/main/res/layout/list_channel_grid_item.xml
  app/src/main/res/values/dimens.xml
Labels: feature request, GUI

#9310 FR: Full width thumbnails aka card view mode
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/InfoListAdapter.java
  app/src/main/java/org/schabi/newpipe/info_list/ItemViewMode.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/PlaylistCardInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/StreamCardInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
  app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/local/feed/item/StreamItem.kt
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistCardItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistStreamCardItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalStatisticStreamCardItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistCardItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/ThemeHelper.java
  app/src/main/res/layout/list_playlist_card_item.xml
  app/src/main/res/layout/list_stream_card_item.xml
  app/src/main/res/layout/list_stream_playlist_card_item.xml
  app/src/main/res/values-w820dp/dimens.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/values/strings.xml
Labels: feature request, GUI

#9651 Added Odia language to language selector
  app/src/main/res/values/settings_keys.xml
Labels: localisation / translation

#9696 Fix NPEs after OnSharedPreferenceChangeListener changes
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/BaseListFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.java
  app/src/main/java/org/schabi/newpipe/local/BaseLocalListFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedFragment.kt
  app/src/main/java/org/schabi/newpipe/settings/VideoAudioSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/tabs/TabsManager.java
  app/src/main/java/us/shandian/giga/service/DownloadManagerService.java
Labels: bug

#9709 Fix reproducible builds
  app/build.gradle
Labels: meta

#9706 Fixed a bug that caused the background player to stop working
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlayQueue.java
  app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java
Labels: bug, player

#9631 Update NewPipeExtractor and properly linkify comments
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentsMiniInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/text/CommentTextOnTouchListener.java
  app/src/main/java/org/schabi/newpipe/util/text/HashtagLongPressClickableSpan.java
  app/src/main/java/org/schabi/newpipe/util/text/TextLinkifier.java
  app/src/main/java/org/schabi/newpipe/util/text/TimestampLongPressClickableSpan.java
Labels: codequality

#9538 Handle duplicate streams in the "Add to playlist" dialog
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistDuplicatesEntry.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalPlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java
  app/src/main/res/layout/dialog_playlists.xml
  app/src/main/res/values/strings.xml
Labels: feature request, playlist

#9725 [YouTube] Add support for live links
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: feature request, youtube

#9726 Fix opening URLs in browser on API 30+
  app/src/main/AndroidManifest.xml
Labels: bug, device/software specific
