Repository TeamNewPipe/NewPipe, pull requests merged in 2024-11, with the labels that each got.

#11566 Fixed playlist order
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
Labels: bug, GUI, database, playlist, size/small, waiting for review

#11694 Fix a typo in README
  README.md
Labels: size/small

#11696 Only start playing single item in history screen
  app/src/main/java/org/schabi/newpipe/local/history/StatisticsPlaylistFragment.java
Labels: size/small

#11024 Adjust the playlist bookmark item layout for RTL languages
  app/src/main/res/layout/list_playlist_bookmark_item.xml
Labels: GUI, size/small

#11711 Actually fix playlist bookmark layout
  app/build.gradle
  app/src/main/res/layout/list_playlist_bookmark_item.xml
Labels: size/small

#10892 update README.fr.md
  doc/README.fr.md
Labels: meta, localisation / translation, size/small

#11268 Update user agent to Firefox ESR 128
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
Labels: privacy & data protection, size/small

#11330 Apply URL encode/decode changes
  app/src/main/java/org/schabi/newpipe/error/ReCaptchaActivity.java
  app/src/main/java/org/schabi/newpipe/settings/DownloadSettingsFragment.java
Labels: codequality, size/small

#11723 Migrate to Coil 3
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/App.kt
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/local/feed/FeedViewModel.kt
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/player/seekbarpreview/SeekbarPreviewThumbnailHolder.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/settings/SettingMigrations.java
  app/src/main/java/org/schabi/newpipe/ui/components/items/playlist/PlaylistThumbnail.kt
  app/src/main/java/org/schabi/newpipe/ui/components/items/stream/StreamThumbnail.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/comment/Comment.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/comment/CommentRepliesHeader.kt
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/java/org/schabi/newpipe/util/ReleaseVersionUtil.kt
  app/src/main/java/org/schabi/newpipe/util/external_communication/ShareUtils.java
  app/src/main/java/org/schabi/newpipe/util/image/CoilHelper.kt
Labels: dependency, size/giant, rewrite

#11743 Throttle feed loading to avoid YouTube rate limits
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadManager.kt
Labels: youtube, feed, size/small

#11714 Add support for secondary audio track type
  app/src/main/java/org/schabi/newpipe/util/ListHelper.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/res/values/strings.xml
Labels: downloader, player, size/small

#11752 Sort dependencies in `libs.versions.toml`
  app/build.gradle
  app/check-dependencies.gradle
  gradle/libs.versions.toml
Labels: dependency, size/medium

#11282 Migrate about activity to Jetpack Compose
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/about/AboutActivity.kt
  app/src/main/java/org/schabi/newpipe/about/License.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragment.kt
  app/src/main/java/org/schabi/newpipe/about/LicenseFragmentHelper.kt
  app/src/main/java/org/schabi/newpipe/about/SoftwareComponent.kt
  app/src/main/java/org/schabi/newpipe/about/StandardLicenses.kt
  app/src/main/java/org/schabi/newpipe/ktx/Bundle.kt
  app/src/main/java/org/schabi/newpipe/ui/components/about/AboutTab.kt
  app/src/main/java/org/schabi/newpipe/ui/components/about/Library.kt
  app/src/main/java/org/schabi/newpipe/ui/components/about/LibraryDefinitions.kt
  app/src/main/java/org/schabi/newpipe/ui/components/about/LicenseDialog.kt
  app/src/main/java/org/schabi/newpipe/ui/components/about/LicenseTab.kt
  app/src/main/java/org/schabi/newpipe/ui/components/about/LicenseTabViewModel.kt
  app/src/main/java/org/schabi/newpipe/ui/components/common/ScaffoldWithToolbar.kt
  app/src/main/java/org/schabi/newpipe/ui/screens/AboutScreen.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_licenses.xml
  app/src/main/res/layout/item_software_component.xml
  app/src/main/res/values/donottranslate.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/libs.versions.toml
Labels: GUI, size/giant, rewrite

#11734 Fix player resuming from start when clicking on a timestamp
  app/src/main/java/org/schabi/newpipe/player/Player.java
Labels: bug, player, size/small

#11738 Always allow changing player notification preferences on Android 13+
  app/src/main/java/org/schabi/newpipe/settings/NotificationsSettingsFragment.kt
Labels: device/software specific, player notification, size/small

#11765 Add build-release-apk workflow
  .github/workflows/build-release-apk.yml
Labels: size/small
