Repository TeamNewPipe/NewPipe, pull requests merged in 2024-03, with the labels that each got.

#10908 Update workflows to use Node 20
  .github/workflows/ci.yml
Labels: meta, size/small

#10717 Calculate cache key based on info type instead of item type
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/util/ExtractorHelper.java
  app/src/main/java/org/schabi/newpipe/util/InfoCache.java
Labels: bug, channel, size/medium

#9975 Changed the landscape layout of list card item
  app/src/main/res/layout-land/list_stream_card_item.xml
Labels: feature request, GUI, size/small

#8242 Trim search string and remove duplicate records from the database
  app/schemas/org.schabi.newpipe.database.AppDatabase/8.json
  app/src/androidTest/java/org/schabi/newpipe/database/DatabaseMigrationTest.kt
  app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java
  app/src/main/java/org/schabi/newpipe/database/AppDatabase.java
  app/src/main/java/org/schabi/newpipe/database/Migrations.java
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
Labels: feature request, database

#10781 BaseDescriptionFragment: Assert member is initialized
  app/src/main/java/org/schabi/newpipe/fragments/detail/BaseDescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelAboutFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/list/channel/ChannelFragment.java
Labels: codequality, size/medium

#6045 show overall duration of videos in playlist
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: feature request, discussion, GUI, playlist, size/medium

#8221 Sort bookmarked playlists
  app/schemas/org.schabi.newpipe.database.AppDatabase/9.json
  app/src/androidTest/java/org/schabi/newpipe/database/DatabaseMigrationTest.kt
  app/src/main/java/org/schabi/newpipe/NewPipeDatabase.java
  app/src/main/java/org/schabi/newpipe/database/AppDatabase.java
  app/src/main/java/org/schabi/newpipe/database/Migrations.java
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistDuplicatesEntry.java
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistLocalItem.java
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistMetadataEntry.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistRemoteDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistStreamDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/model/PlaylistEntity.java
  app/src/main/java/org/schabi/newpipe/database/playlist/model/PlaylistRemoteEntity.java
  app/src/main/java/org/schabi/newpipe/fragments/MainFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/local/LocalItemListAdapter.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/BookmarkFragment.java
  app/src/main/java/org/schabi/newpipe/local/bookmark/MergedPlaylistManager.java
  app/src/main/java/org/schabi/newpipe/local/dialog/PlaylistAppendDialog.java
  app/src/main/java/org/schabi/newpipe/local/holder/LocalBookmarkPlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/RemoteBookmarkPlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/holder/RemotePlaylistItemHolder.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistManager.java
  app/src/main/java/org/schabi/newpipe/local/playlist/RemotePlaylistManager.java
  app/src/main/java/org/schabi/newpipe/settings/SelectPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/util/debounce/DebounceSavable.java
  app/src/main/java/org/schabi/newpipe/util/debounce/DebounceSaver.java
  app/src/main/res/layout/list_playlist_bookmark_item.xml
  app/src/test/java/org/schabi/newpipe/database/playlist/PlaylistLocalItemTest.java
Labels: feature request, GUI, playlist, size/giant

#9580 Moved player notification setting to notification section
  app/src/main/res/xml/appearance_settings.xml
  app/src/main/res/xml/notifications_settings.xml
Labels: bug, size/small
