Repository TeamNewPipe/NewPipe, pull requests merged in 2024-04, with the labels that each got.

#10959 Fix not saving comment replies state on config change
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentRepliesFragment.java
Labels: bug, GUI, size/small

#10957 Fix NPE if avatarUrl is null when reloading feed
  app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionEntity.java
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedUpdateInfo.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
Labels: bug, feed, size/small

#10952 Add an intuitive prefix for the duration of lists in the UI
  app/src/main/java/org/schabi/newpipe/fragments/list/playlist/PlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: GUI, size/small

#10992 Fix free storage space check for all APIs
  app/src/main/java/org/schabi/newpipe/download/DownloadDialog.java
  app/src/main/java/org/schabi/newpipe/streams/io/StoredDirectoryHelper.java
  app/src/main/java/us/shandian/giga/util/Utility.java
Labels: downloader, size/medium

#11003 Update README.md
  README.md
Labels: meta, size/small

#11014 Fix github worklow for Android tests
  .github/workflows/ci.yml
Labels: CI, size/small
