Repository TeamNewPipe/NewPipe, pull requests merged in 2025-04, with the labels that each got.

#12150 [YouTube] Access first element if array size is one
  app/src/main/java/org/schabi/newpipe/util/potoken/JavaScriptUtil.kt
Labels: bug, youtube, size/small

#12117 Show download date of downloaded videos
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/res/layout/mission_item.xml
  app/src/main/res/layout/mission_item_linear.xml
Labels: feature request, downloader, size/small

#12195 Merge dev to refactor
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/java/org/schabi/newpipe/util/potoken/JavaScriptUtil.kt
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
  app/src/main/res/layout/mission_item.xml
  app/src/main/res/layout/mission_item_linear.xml
  app/src/main/res/resources.properties
  app/src/main/res/values/settings_keys.xml
  app/src/main/res/xml/content_settings.xml
  gradle/libs.versions.toml
Labels: size/medium
