Repository TeamNewPipe/NewPipe, pull requests merged in 2025-05, with the labels that each got.

#12256 build.gradle: Improve jitpack workaround doc & fix hash
  app/build.gradle
Labels: size/small

#12188 fix: support RTL usernames in comment header
  app/src/main/java/org/schabi/newpipe/info_list/holder/CommentInfoItemHolder.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: bug, GUI, size/small, comments

#12259 Comments: Put @ on the right side of right-to-left usernames
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: bug, GUI, size/small, comments

#11789 Fix background crash focus
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
Labels: bug, size/small

#11829 Player UI list to kotlin
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.java
  app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
  app/src/main/java/org/schabi/newpipe/util/GuardedByMutex.kt
Labels: player, codequality, size/large, rewrite

#11759 Rewrite import and export subscriptions functionality using coroutines
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/database/subscription/SubscriptionDAO.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/ImportConfirmationDialog.java
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionManager.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionsImportFragment.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/BaseImportExportService.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/ImportExportEventListener.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelper.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsExportService.java
  app/src/main/java/org/schabi/newpipe/local/subscription/services/SubscriptionsImportService.java
  app/src/main/java/org/schabi/newpipe/local/subscription/workers/ImportExportJsonHelper.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/workers/SubscriptionData.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/workers/SubscriptionExportWorker.kt
  app/src/main/java/org/schabi/newpipe/local/subscription/workers/SubscriptionImportWorker.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelperTest.java
  build.gradle
  gradle/libs.versions.toml
Labels: feature request, dependency, size/giant, rewrite, import/export

#12298 Add dev and refactor nightly build badges
  README.md
Labels: size/small
