Repository TeamNewPipe/NewPipe, pull requests merged in 2025-01, with the labels that each got.

#11879 Fix image-minimizer on lines containing multiple images
  .github/workflows/image-minimizer.js
Labels: size/small

#11928 Fix the issue of getting the checksum of a removed file
  app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java
Labels: bug, downloader, size/small

#11806 Fix caption sizes not being changed
  app/src/main/java/org/schabi/newpipe/player/ui/MainPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/ui/VideoPlayerUi.java
Labels: bug, GUI, player, size/small

#11867 PlayerHolder refactor
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerEventListener.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerHolderLifecycleEventListener.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceEventListener.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceExtendedEventListener.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
Labels: player, codequality, size/medium, rewrite

#11870 Add link to donation page on app drawer
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/res/drawable-mdpi/volunteer_activism_ic.xml
Labels: feature request, template missing, size/small

#11959 Fix loading StreamInfo twice on first VideoDetailFragment opening
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: bug, size/small

#11539 Compose theme improvements
  app/src/main/java/org/schabi/newpipe/fragments/list/comments/CommentsFragment.kt
  app/src/main/java/org/schabi/newpipe/fragments/list/videos/RelatedItemsFragment.kt
  app/src/main/java/org/schabi/newpipe/ui/Toolbar.kt
  app/src/main/java/org/schabi/newpipe/ui/components/common/LoadingIndicator.kt
  app/src/main/java/org/schabi/newpipe/ui/components/common/Scrollbar.kt
  app/src/main/java/org/schabi/newpipe/ui/components/items/playlist/PlaylistListItem.kt
  app/src/main/java/org/schabi/newpipe/ui/components/items/stream/StreamListItem.kt
  app/src/main/java/org/schabi/newpipe/ui/components/items/stream/StreamMenu.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/RelatedItems.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/comment/Comment.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/comment/CommentRepliesDialog.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/comment/CommentRepliesHeader.kt
  app/src/main/java/org/schabi/newpipe/ui/components/video/comment/CommentSection.kt
  app/src/main/java/org/schabi/newpipe/ui/theme/Color.kt
  app/src/main/java/org/schabi/newpipe/ui/theme/Theme.kt
  app/src/main/res/values/colors.xml
Labels: GUI, size/large, rewrite

#11969 DownloaderImpl: Auto-close resources and simplify header setting
  app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
Labels: bug, codequality, size/small
