Repository TeamNewPipe/NewPipe, pull requests merged in 2025-02, with the labels that each got.

#11955 [YouTube] Add support for poTokens
  app/build.gradle
  app/src/main/assets/po_token.html
  app/src/main/java/org/schabi/newpipe/App.java
  app/src/main/java/org/schabi/newpipe/player/datasource/YoutubeHttpDataSource.java
  app/src/main/java/org/schabi/newpipe/util/DeviceUtils.java
  app/src/main/java/org/schabi/newpipe/util/potoken/JavaScriptUtil.kt
  app/src/main/java/org/schabi/newpipe/util/potoken/PoTokenException.kt
  app/src/main/java/org/schabi/newpipe/util/potoken/PoTokenGenerator.kt
  app/src/main/java/org/schabi/newpipe/util/potoken/PoTokenProviderImpl.kt
  app/src/main/java/org/schabi/newpipe/util/potoken/PoTokenWebView.kt
Labels: bug, ASAP, youtube, size/giant

#12046 Update translations
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bar/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-gu/strings.xml
  app/src/main/res/values-hy/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-vmf/strings.xml
  fastlane/metadata/android/de/changelogs/1003.txt
  fastlane/metadata/android/et/changelogs/1003.txt
  fastlane/metadata/android/et/changelogs/998.txt
  fastlane/metadata/android/et/changelogs/999.txt
  fastlane/metadata/android/et/full_description.txt
  fastlane/metadata/android/et/short_description.txt
  fastlane/metadata/android/fr/changelogs/1002.txt
  fastlane/metadata/android/fr/changelogs/1003.txt
  fastlane/metadata/android/hu/changelogs/1002.txt
  fastlane/metadata/android/hu/changelogs/1003.txt
  fastlane/metadata/android/ka/changelogs/1002.txt
  fastlane/metadata/android/ka/changelogs/1003.txt
  fastlane/metadata/android/ka/changelogs/65.txt
  fastlane/metadata/android/ka/changelogs/68.txt
  fastlane/metadata/android/ka/changelogs/69.txt
  fastlane/metadata/android/ne/short_description.txt
  fastlane/metadata/android/sk/changelogs/1000.txt
  fastlane/metadata/android/sk/changelogs/1002.txt
  fastlane/metadata/android/sk/full_description.txt
  fastlane/metadata/android/sk/short_description.txt
  fastlane/metadata/android/sv/changelogs/1003.txt
Labels: size/large

#12035 Ugly fix for broken text colors in dark mode
  app/src/main/java/org/schabi/newpipe/MainActivity.java
Labels: bug, GUI, size/small

#11978 MainActivity: Fix onBackPressed handling for open player
  app/src/main/java/org/schabi/newpipe/MainActivity.java
Labels: bug, player, queue, size/small, rewrite

#12067 Fix stream notification grouping
  app/src/main/java/org/schabi/newpipe/local/feed/notifications/NotificationHelper.kt
Labels: bug, new stream notification, size/small
