Repository TeamNewPipe/NewPipe, pull requests merged in 2025-03, with the labels that each got.

#12065 Share as YouTube temporary playlist
  app/src/main/java/org/schabi/newpipe/local/playlist/ExportPlaylist.kt
  app/src/main/java/org/schabi/newpipe/local/playlist/LocalPlaylistFragment.java
  app/src/main/java/org/schabi/newpipe/local/playlist/PlayListShareMode.java
  app/src/main/res/values-ar-rLY/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-be/strings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-is/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-or/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-pt-rPT/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-ryu/strings.xml
  app/src/main/res/values-sat/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/schabi/newpipe/local/playlist/ExportPlaylistTest.kt
Labels: size/large

#12089 Disambiguate audio track labels
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: size/small

#12104 Update NewPipe Extractor and add new proguard rules
  app/build.gradle
  app/proguard-rules.pro
Labels: meta, dependency, size/small

#12044 Add support for Android Auto *(season 2)*
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/database/history/model/StreamHistoryEntry.kt
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistLocalItem.java
  app/src/main/java/org/schabi/newpipe/database/playlist/PlaylistMetadataEntry.java
  app/src/main/java/org/schabi/newpipe/database/playlist/dao/PlaylistRemoteDAO.java
  app/src/main/java/org/schabi/newpipe/database/playlist/model/PlaylistRemoteEntity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/ktx/Bundle.kt
  app/src/main/java/org/schabi/newpipe/local/playlist/RemotePlaylistManager.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/event/PlayerServiceExtendedEventListener.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserCommon.kt
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserImpl.kt
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserPlaybackPreparer.kt
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/AbstractInfoPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/playqueue/PlaylistPlayQueue.java
  app/src/main/java/org/schabi/newpipe/player/ui/PopupPlayerUi.java
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
  app/src/main/res/drawable/ic_bookmark_white.xml
  app/src/main/res/drawable/ic_history_white.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/automotive_app_desc.xml
Labels: feature request, device/software specific, size/giant
