Repository TeamNewPipe/NewPipe, pull requests merged in 2025-07, with the labels that each got.

#12356 check if the JSON MimeType is supported
  app/src/main/java/org/schabi/newpipe/local/subscription/SubscriptionFragment.kt
Labels: bug, size/small, import/export, ready for review

#12410 Fix thumbnails appearing on Android Auto even if disabled
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserImpl.kt
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserPlaybackPreparer.kt
Labels: bug, player, device/software specific, size/small, Android Auto

#12415 Migrate zip import/export to use Path
  app/src/main/java/org/schabi/newpipe/settings/BackupRestoreSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/settings/export/BackupFileLocator.kt
  app/src/main/java/org/schabi/newpipe/settings/export/ImportExportManager.kt
  app/src/main/java/org/schabi/newpipe/util/ZipHelper.java
  app/src/test/java/org/schabi/newpipe/settings/ImportAllCombinationsTest.kt
  app/src/test/java/org/schabi/newpipe/settings/ImportExportManagerTest.kt
Labels: bug, codequality, size/medium, rewrite

#12412 Fix ghost notifications on Android 10; fix MediaBrowser exposed
  app/src/main/java/org/schabi/newpipe/player/PlayerService.java
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserImpl.kt
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/PackageValidator.kt
Labels: bug, ASAP, player, player notification, size/large

#12258 SearchFragment: show service name in search hint
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
  app/src/main/res/values/strings.xml
Labels: feature request, GUI, multiservice, size/small, search, ready for review

#12337 Refactor: Video detail fragment kotlin conversion
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/RouterActivity.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.kt
  app/src/main/java/org/schabi/newpipe/info_list/dialog/InfoItemDialog.java
  app/src/main/java/org/schabi/newpipe/player/PlayQueueActivity.java
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/PlayerService.kt
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.java
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHolder.kt
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/MediaBrowserImpl.kt
  app/src/main/java/org/schabi/newpipe/player/mediasession/MediaSessionPlayerUi.java
  app/src/main/java/org/schabi/newpipe/player/notification/NotificationUtil.java
  app/src/main/java/org/schabi/newpipe/player/ui/PlayerUiList.kt
  app/src/main/java/org/schabi/newpipe/ui/components/items/stream/StreamMenu.kt
  app/src/main/java/org/schabi/newpipe/util/NavigationHelper.java
Labels: codequality, size/giant, rewrite

#12434 Fix new badge links on Readme being rendered incorrectly
  README.md
  doc/README.ar.md
  doc/README.asm.md
  doc/README.de.md
  doc/README.es.md
  doc/README.fr.md
  doc/README.hi.md
  doc/README.it.md
  doc/README.ja.md
  doc/README.ko.md
  doc/README.pa.md
  doc/README.pl.md
  doc/README.pt_BR.md
  doc/README.ro.md
  doc/README.ru.md
  doc/README.ryu.md
  doc/README.so.md
  doc/README.sr.md
  doc/README.tr.md
  doc/README.zh_TW.md
Labels: meta, size/medium

#12388 Target SDK 35
  .github/workflows/ci.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/error/ErrorUtil.kt
  app/src/main/java/org/schabi/newpipe/fragments/detail/VideoDetailFragment.java
  app/src/main/java/org/schabi/newpipe/local/feed/service/FeedLoadService.kt
  app/src/main/java/org/schabi/newpipe/player/Player.java
  app/src/main/java/org/schabi/newpipe/player/mediabrowser/PackageValidator.kt
  app/src/main/res/values-v35/styles.xml
Labels: dependency, size/medium

#12455 Use correct fix for nextPage being null while creating error report
  app/src/main/java/org/schabi/newpipe/fragments/list/search/SearchFragment.java
Labels: bug, size/small, search

#12470 Improve and cleanup PlayerHelper formatters/localization
  app/src/main/java/org/schabi/newpipe/player/helper/PlayerHelper.java
  app/src/main/java/org/schabi/newpipe/settings/ContentSettingsFragment.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
Labels: player, codequality, size/medium

#12450 Add SettingsMigration to change YouTube trending kiosk tab
  app/build.gradle
  app/src/main/java/org/schabi/newpipe/MainActivity.java
  app/src/main/java/org/schabi/newpipe/settings/NewPipeSettings.java
  app/src/main/java/org/schabi/newpipe/settings/migration/MigrationManager.java
  app/src/main/java/org/schabi/newpipe/settings/migration/SettingMigrations.java
  app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java
  app/src/main/java/org/schabi/newpipe/util/Localization.java
  app/src/main/res/drawable/ic_podcasts.xml
  app/src/main/res/menu/drawer_items.xml
  app/src/main/res/values-ti/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature request, youtube, requires extractor change, size/large
